RipMeApp/ripme

- src/main/java/com/rarchives/ripme/ripper/rippers/ImgurRipper.java
I removed a block of javascript parsing code that would always fail and changed getAlbumTitle so it would never return the default album title (Just the album ID)
> Removed dead code from imgur ripper and improved getAlbumTitle

- src/main/java/com/rarchives/ripme/ripper/rippers/AerisdiesRipper.java
A ripper for aerisdies.com.
Test link: http://www.aerisdies.com/html/lb/douj_11369_1.html
> Added basic support for aerisdies.com

- src/main/java/com/rarchives/ripme/ripper/rippers/EroShareRipper.java
This allows users to rip eroshare (Now down and never coming back) albums using a mirror. Some content will 404 because it wasn't archived before eroshare went down
> Eroshareripper now uses mirror for data

- src/main/java/com/rarchives/ripme/ripper/rippers/ImagearnRipper.java
The ripper now rips image from each album page instead of using the thumbnail to get the full sized image
> Fixed ImagearnRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/EromeRipper.java
A ripper for erome that supports pictures and videos. It closes #36 
Test links:
https://www.erome.com/a/ixVfLNtQ - album of videos
https://www.erome.com/a/n3d8WIxW - album with a single video
https://www.erome.com/a/8g2TCiPp - album mixed
https://www.erome.com/a/gEgcLsOG - album of pictures
> Added ripper for erome.com

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
I updated the cdn url (So downloading images no longer throws 404s) and changed how the ripper tells if it is ripping a album or a series of sub-albums*
* I used a regex to do this, but the regex will fail for comics who titles are all numbers, if anyone can think of a better way to do this please let me know
The regex I used ```/comix/[a-zA-Z0-9\\-_/]*/\\d+```
Test links:
Single album: https://www.8muses.com/comix/album/prismgirls-comics/bikini-space-police
Sub-albums: https://www.8muses.com/comix/album/the-foxxx-comics/the-anal-plumber
~~edit: I found an error, don't merge yet~~
~~Edit_2: I add a hackish workaround for the error I ran into~~ …
> Fixed 8muses ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
* These changes to the getOriginalUrl should make sure that the InstagramRipper stops retrieving the cropped versions of the images.
>  InstagramRipper getOriginalUrl retrieving cropped images fix

- src/main/java/com/rarchives/ripme/ripper/rippers/ImagefapRipper.java
This fixes bug #79. This adds the album GID to the folder name so 2 albums with the same name are no long written to the same folder
> [Imagefap] Now adds GID to folder name when using album name as floder name

- src/main/java/com/rarchives/ripme/ripper/rippers/NhentaiRipper.java
Nhentai albums now include nhentai in the folder name
> Nhentai links now inculde nhentai in the folder title

- src/main/java/com/rarchives/ripme/ripper/rippers/CfakeRipper.java
A ripper for cfake.com 
Test link: http://cfake.com/picture/Olivia-Munn/969/
> Added cfake.com ripper

- src/main/java/com/rarchives/ripme/App.java
Added a -v, --version option for CLI. Relevant with  issue #49  
> Added -v, --version flag

- src/main/java/com/rarchives/ripme/App.java
- src/main/java/com/rarchives/ripme/ui/MainWindow.java
- src/main/java/com/rarchives/ripme/utils/Utils.java
Ripme checks its config and history file in OS default config directory. 
`%LOCALAPPDATA%\ripme` for Windows
`~/Library/Application Support/` for Mac OS
` ~/.config/ripme` for other Unix-like
> Default config paths added

- src/main/java/com/rarchives/ripme/ripper/rippers/MyhentaicomicsRipper.java
The ripper now checks if a link starts with http or https and if so skips it (Because on this site only ads start with either)
NSFW
Test link: http://myhentaicomics.com/index.php/Special-Training-DB
> Myhentaicomics ripper no longer tries to download ads

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaiCafeRipper.java
A ripper for single comics from hentai.cafe
Test link
https://hentai.cafe/coupe-blue-eyes-and-candied-strawberries/
> Added hentai.cafe ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/SankakuComplexRipper.java
A fix for sankakucomplex (It now downloads full sized images)
> Fixed sankakucomplex ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/HbrowseRipper.java
> Added Hbrowse.com ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
The ripper now can tell albums from sub albums all of the time (Or at least almost all the time), has ASAP ripping for subalbums and preserves the folder structure of subalbums 
There is a minor bug in the ripper that causes it to make some empty folders 
Test link: https://www.8muses.com/comix/album/taboolicious_xxx-comics
> 8muses ripper now can rip from all album types

- src/main/java/com/rarchives/ripme/ripper/rippers/video/XhamsterRipper.java
I've modified the regex to account for either a /movies or /videos subdir.
> Fixes RipMeApp/ripme#57

- src/main/java/com/rarchives/ripme/ripper/rippers/ImgboxRipper.java
A few minor changes to the regex what changes the thumbnail url to the full image url
There's already a unit test
> Fixed imgbox ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/ShesFreakyRipper.java
The ripper now adds https: to the image links it tries to download, meaning the links no longer throw no protocol errors
> Fixed shesfreaky.com ripper

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This removes the confusing "We've moved" comments from the PR and Issue templates, since the move is done and it's somewhat confusing for people, as it points to this repository.
> Updated issue and PR templates

- src/main/java/com/rarchives/ripme/ui/MainWindow.java
The log, history, and queue are hard to read with a small unresizable window. This makes the window resizable when the lower panes are not visible.
All the tests that fail also fail on the current main master branch. The failures are not related to these changes.
> Make expanded window resizable

- src/main/java/com/rarchives/ripme/ui/MainWindow.java
It is confusing for the window to only be resizable when it is expanded, so this makes the window always resizable. (see #122)
> Make window always resizable

- src/main/java/com/rarchives/ripme/ripper/rippers/PorncomixRipper.java
A ripper for porncomix.info
Test link: http://www.porncomix.info/edge-of-humanity-01-zzz/
> Added Porncomix.info ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/Hentai2readRipper.java
A ripper for hentai2read.com
Test links:
https://hentai2read.com/okaasan_boku_onna_ni_natte_mo_ii
https://hentai2read.com/0_distance_love
> Added hentai2read ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/WebtoonsRipper.java
A ripper for the site webtoons.com
Test link: http://www.webtoons.com/en/fantasy/the-gamer/ep-1/viewer?title_no=88&episode_no=1
> Added Webtoons ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/ImgboxRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/BasicRippersTest.java
fixed imgbox ripper; removed unit test for site that doesn't exist anymore
> fixed Imgbox ripper; removed unti test for site that doesn't exist anymore

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/BasicRippersTest.java
I changed the ripper gets the full sized image url
> 8muses ripper now works with latest site update

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/InstagramRipperTest.java
I rewrote some of the instagram ripper so it now can download images/videos without needing the /media endpoint
> Fixed instagram ripper

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ui/MainWindow.java
- src/main/java/com/rarchives/ripme/utils/Utils.java
I added the ability for ripme to remember and skip urls that it has downloaded in the past
> Remember downloaded URLs

- .travis.yml
- README.md
Changes the TravisCI configuration to make it work on the current environment and build against OpenJDK8 and Oracle JDK8 (In order to ensure that everyone can use it and to be able to spot JVM-related bugs quicker).
This was tested using my account, you can read the logs there: https://travis-ci.org/MrTimscampi/ripme  
Note that the builds fail due to unit tests failing, but the build completes (which is what is important, at this stage).
A member of the RipMeApp organization should enable Travis (Easy to do, just go login on TravisCI and enable the repo) to complete this PR.
Another change that would be interesting but can only be done by someone from the organization is to enable Travis to …
> Updated TravisCI configuration

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaiCafeRipper.java
> Minor formatting fix for HentaiCafe ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/ImgurRipper.java
I added another regex check so imgur /t albums now pass
> Added support for imgur /t albums

- src/main/java/com/rarchives/ripme/utils/Utils.java
Ripme will run in portable mode (It writes all config files to the same dir as the jar) if a file named rip.properties exists in the dir the jar is run from
> Added portable mode

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
Urls are now only added to the url_history file if ripme is not being run in testmode 
> Remembering url history no longer causes unit tests to fail

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
The ripper now returns the page title if the thread title is null
> Fixed chan ripper thread title (For real this time)

- src/main/java/com/rarchives/ripme/ripper/rippers/WebtoonsRipper.java
I changed the webtoons malformed url error message to the standard one
> Fixed webtoons malformed url error message

- src/main/java/com/rarchives/ripme/ripper/rippers/ViewcomicRipper.java
I added a ripper for the site view-comic.com
> Added viewcomic ripper

- src/main/java/com/rarchives/ripme/utils/Utils.java
I added a util function (Taken from 4pr0n/ripme#354) for getting site cookies from the config file
> Added getCookies func

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/BasicRippersTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/InstagramRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/RippersTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/VideoRippersTest.java
Opened #181 #182 #183 #185 #186 #187
Fixes #21
Fix and disable failing tests to get CI builds to be green.
> Fix RippersTest and disable other failing tests

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
I changed the album title fall back from the page title, to the hostname and album GID and added a regex to match xchan 
> chanRipper now falls back to  getHost() and getGID(), not page title

- src/main/java/com/rarchives/ripme/ripper/rippers/TheyiffgalleryRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/BasicRippersTest.java
I added a ripper for theyiffgallery
> Added ripper for theyiffgallery

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
When downloading a file from instagram the ripper ripper now includes the date the image was posted in the file name, I also added support for ripping single posts (Both video and image) and moved from abstractJSONRipper to abstractHTMLRipper because abstractJSONRipper was unable to rip single posts
> Change to IG ripper filename format and move from JSON ripper to HTML

- src/main/java/com/rarchives/ripme/utils/Utils.java
For example, kb is incorrect because lowercase k is not a correct abbreviation of kilo- and lowercase b means bits not Bytes. Correct abbreviation would be KB (if dividing by 1000 at each magnitude) or KiB (if dividing by 1024 at each magnitude). Since we are using the latter, update display to be e.g. KiB, MiB instead of kb, mb.
> Update size abbreviations e.g. from kb, mb, to KiB, MiB

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
- src/main/java/com/rarchives/ripme/utils/Utils.java
Prefix for file name was not sanitized in any way. Now it is sanitized with `Utils.filesystemSanitized` which converts all unacceptable characters to `_`, but not as extreme as `Utils.filesystemSafe` which also deduplicates `_` and strips them from the end.
> Fix #211: Add Utils.filesystemSanitized and apply to filename prefix.

- src/main/java/com/rarchives/ripme/ripper/rippers/PichunterRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/BasicRippersTest.java
Added support for pichunter galleries
> Pichunter galleries support

- src/main/java/com/rarchives/ripme/ripper/rippers/PichunterRipper.java
I tweaked the regex to match any non-white space when getting the GID
> Improved regex for pichunter.com

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
I improved the regex to allow for /?hl=$LANG to come after the url and added and added a sanitizeURL() func
> Improved instagram regex and added sanitizeURL

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
I added the ability to rip from instagram hashtags
> Added support for ripping from IG tags

- README.md
- pom.xml
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImagefapRipperTest.java
Added code coverage at https://coveralls.io/github/RipMeApp/ripme
This PR includes changes necessary to get this to work with TravisCI.
> Add code coverage with coveralls.io; Issue #226: Temporarily disable ImagefapRipperTest

- src/main/java/com/rarchives/ripme/App.java
- src/main/java/com/rarchives/ripme/ripper/rippers/E621Ripper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/PahealRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/XbooruRipper.java
- src/main/java/com/rarchives/ripme/utils/Http.java
Not consistently using log4j and using wrong class names for loggers for some rippers.
> Fix loggers

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/PhotobucketRipperTest.java
Re-enable PhotobucketRipperTest, pages are now loading just fine
> Close #229: re-enable PhotobucketRipperTest, pages are now loading just fine

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImagefapRipperTest.java
fap.to is back up and rips are working again: restore unit test
> Close #226: re-enable ImagefapRipperTest

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/SankakuComplexRipperTest.java
Re-enable SankakuComplexRipperTest. SankakuComplexRipper seems to have been fixed in #99 (@cyian-1756).
> Re-enable SankakuComplexRipperTest

- src/main/java/com/rarchives/ripme/ripper/rippers/WebtoonsRipper.java
The ripper now includes the site name in the album title
> Improved webtoons folder naming

- src/main/java/com/rarchives/ripme/ripper/rippers/WordpressComicRipper.java
freeadultcomix.com no longer needs to add domain to image links (and in fact was broken because it did)
> Fix WordpressComicRipper's ripper for freeadultcomix.com

- src/main/java/com/rarchives/ripme/ripper/rippers/FuraffinityRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FuraffinityRipperTest.java
Replaces #176 by @cyian-1756
I removed all the code for logging in (Which ripme was not able to go anymore due to a change in the login system) so the ripper can now rip all public albums.
> Fix furaffinity

- src/main/java/com/rarchives/ripme/ripper/rippers/WordpressComicRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/WordpressComicRipperTest.java
Add WordpressComicRipperTest, fix and clean up issues it revealed.
> Add WordpressComicRipperTest; remove dead site comics-xxx.com

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/InstagramRipperTest.java
I added support for ripping from single pages on instagram (Both single picture/video and slideshows)
> Added support for ripping single pages from instagram

- src/main/java/com/rarchives/ripme/ripper/rippers/AerisdiesRipper.java
I changed up the GID regex and the getAlbumTitle so it now includes the album title in the folder name
Test link: http://www.aerisdies.com/html/lb/alb_3692_1.html
> Minor improvements to Aerisdies folder naming

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
The ripper now downloads all images in slide shows when ripping entire user profiles
Test link: https://www.instagram.com/hilaryduff/
After the first 48 or so images (as of 22/11/2017) you should see images from the slide show https://www.instagram.com/p/BZ4egP7njW5/ start appearing with the name format of $Date_$postCode_$imageName
> Instagram ripper now downloads slide shows when ripping user profiles

- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/XhamsterRipperTest.java
I rewrote the ripper to the mobile version of the site, meaning we don't have to worry about the tests randomly failing because they got the new beta version of the desktop site
> Xhamster rewrite

- src/main/java/com/rarchives/ripme/ripper/rippers/WordpressComicRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/WordpressComicRipperTest.java
Enable WordpressComicRipper konradokonski.com tests with updated URLs as discussed in #266.
> Fix #266: Enable WordpressComicRipper konradokonski.com tests with updated URLs.

- src/main/java/com/rarchives/ripme/ripper/rippers/CheveretoRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/CheveretoRipperTest.java
hushpix has a consent dialog blocking access to the site which can be bypassed by setting the consent cookie.
> Format CheveretoRipper; implement AGREE_CONSENT cookie for hushpix; add CheveretoRipperTest

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
> Fix #98: Update User Agent to current most common UA (Chrome 61 on Windows 10 x64)

- src/main/java/com/rarchives/ripme/ripper/rippers/OglafRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/OglafRipperTest.java
> Oglaf ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/SankakuComplexRipper.java
The ripper now downloads tehe full sized images
* [X ] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
> SankakuComplexRipper now downloads full sized images

- src/main/java/com/rarchives/ripme/ripper/rippers/ImgurRipper.java
This removes the string "Imgur: The magic of the Internet" from imgur album file names
> Fixed imgur album filenames

- src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java
The ripper now replaces http with https in all links before downloading them, this seems to fix the issue where all tumblr links were throwing 400 errors
> Forced https for tumblr image links

- src/main/java/com/rarchives/ripme/ripper/rippers/DribbbleRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/DribbbleRipperTest.java
> Added dribbble.com ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/EromeRipper.java
The ripper now allows the user to add urls with out a www., and just adds the www. to the url before downloading
> Erome ripper now matchs links without the www

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FuskatorRipperTest.java
Would not work, even if human was looking at it.
**This is probably why all travis.cl builds have not been compiling.**
Updated URL to more popular album. Hopefully it will not get deleted in the future.
New Fuskator link for test suite
Compile and ran on new test URL.
Nothing else should be affected.
> Old Fuskator Test Link Fix

- src/main/java/com/rarchives/ripme/App.java
- src/main/java/com/rarchives/ripme/ripper/AbstractHTMLRipper.java
- src/main/java/com/rarchives/ripme/ripper/AbstractJSONRipper.java
- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ripper/AlbumRipper.java
- src/main/java/com/rarchives/ripme/ripper/DownloadThreadPool.java
- src/main/java/com/rarchives/ripme/ripper/DownloadVideoThread.java
- src/main/java/com/rarchives/ripme/ripper/RipperInterface.java
- src/main/java/com/rarchives/ripme/ripper/VideoRipper.java
There should be no changes to the code. Just a ton of documentation.
It should help newcomers get aquainted with code quicker.
Added Javadocs for App.java and basically all of the classes in 'com.rarchives.ripme.rippper'.
And one small code change:
in app.java:
'if (HISTORY.toList().size() == 0) {' to 'if (HISTORY.toList().isEmpty()) {'
> 3 Metric Tons of Javadoc documentation for core Ripper stuff.

- src/main/java/com/rarchives/ripme/ripper/rippers/PornpicsRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/PornpicsRipperTest.java
I added a ripper for pornpics.com
> Added basic pornpics.com ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaiCafeRipper.java
I change the number range in the regex from 1-9 to 0-9
> Fixed hentai.cafe regex

- src/main/java/com/rarchives/ripme/ripper/rippers/CheveretoRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/CheveretoRipperTest.java
I added gwarchives support to the cheveretoRipper
> Added gwarchives support to the cheveretoRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
If the option `instagram.download_images_only` is true the ripper will skip videos
> instagram ripper can now be made to skip videos

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
The ripper now removes any string matching vp/[a-zA-Z0-9]*/ before downloading an image
> Instagram ripper no longer 403s on certain images

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FuskatorRipperTest.java
> disabled FuskatorRipperTest

- src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java
Fixes API choosing. Creates Random objects, generates a number, then feeds
that number to API_KEY.
This is as opposed to the previous way where it created the Random object,
generated a number, then fed it all in a single line.
Also a bit more Documentation.
Hand tested - in 10 tries:
- 3x JFN...
- 3x qpd...
- 4x FQr...
So all in all, pretty even distribution
Also tested on my own fork using Travis CI [here](https://travis-ci.org/kevin51jiang/ripme/builds/330163606).
> Tumblr API Key Choosing Fix & More Documentation

- src/main/java/com/rarchives/ripme/ripper/rippers/video/PornhubRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/VideoRippersTest.java
Fixes Pornhub ripper bug introduced with website change.
> Pornhub fix

- src/main/java/com/rarchives/ripme/ripper/rippers/WebtoonsRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/WebtoonsRipperTest.java
Previously, the webtoons ripper would download links that looked like `http://webtoon.phinf.naver.net/20180103_245/1514974519142IF53B_JPEG/151497451910910491455.jpg?type=q90`
This  change uses regex to remove the part after the extension, thus allowing the ripper to download the original files without any compression
> Make webtoons ripper download maximum quality images

- src/main/java/com/rarchives/ripme/ripper/rippers/video/TwitchVideoRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/VideoRippersTest.java
Add Twitch.tv video ripper requested in #38 by @painerp
> Twitch ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/CheveretoRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/CheveretoRipperTest.java
Remove ripper and tests for gwarchives.com and hushpix.com
>  Remove ripper and tests for gwarchives.com and hushpix.com

- src/main/java/com/rarchives/ripme/ripper/AlbumRipper.java
- src/main/java/com/rarchives/ripme/utils/Utils.java
This bugfix prevents the creation of multiple directories of the same name with different character cases. Only on Unix-based systems #353 
Code description: 
Getting the filelist of the ./rips directory and compare the lowercase version with existing one. If there is an existing directory, the existing name with correct case will be returned.
> Fix case sensitive directories on unix-based systems

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/EightmusesRipperTest.java
I rewrote the ripping logic so the ripper now supports ripping pages containing both images and subpages 
> 8muses now supports all page types

- src/main/java/com/rarchives/ripme/ui/ClipboardUtils.java
I changed the regex in com/rarchives/ripme/ui/ClipboardUtils.java to include domains ending in .cafe
> Ripme now supports clipboard ripping for .cafe domains

- src/main/java/com/rarchives/ripme/ripper/AlbumRipper.java
I added some directory sanitation  
> AlbumRipper.java now removes bad chars from file names

- src/main/java/com/rarchives/ripme/ripper/AlbumRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/ImgurRipper.java
I fixed the regression caused by 1.7.18 that broke downloading imgur albums on windows
> Windows file system fixes

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MotherlessRipperTest.java
I changed the motherless test url to a gallery that isn't 404ing
> Fixed motherless test

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/EightmusesRipperTest.java
I changed the regex in the ripper to use 8muses new url format
> 8muses fix

- src/main/java/com/rarchives/ripme/ripper/AbstractHTMLRipper.java
- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
I implmented a "last seen" feature which ends the rip if the last X urls have already been downloaded, where X is user supplied with the skip_after_already_seen config option
This closes number #439
> Added a last seen feature

- src/main/java/com/rarchives/ripme/ripper/AbstractHTMLRipper.java
The default value was -1 which caused ripme to end the rip if the user hadn't changed the default value
> Changed default value for history.end_rip_after_already_seen

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
The ripper now uses getNextPage to get the next page instead of doing it in getUrlsFromPage
> lastseen feature now works with instagram

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/WordpressComicRipperTest.java
I commented out a unit test that was randomly failing
> Disabled flaky unit test

- src/main/java/com/rarchives/ripme/ripper/rippers/TsuminoRipper.java
I added a ripper for tsumino.com
> Added tsuminoRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/WordpressComicRipper.java
I added support for incase.buttsimthy.com
> Added support for incase.buttsimthy.com

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
I added support for instagrams new JSON structure and changed to the new api endpoint for getting the next page
> Insagram ripper now can get all pages of a profile

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
I added support for ripping from tags on instagram and made the ripper remove unescaped " marks
> IG ripper can now rip from tags; fixed json parsing issues

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaifoundryRipper.java
I changed the if that detected if there was another page or not
> Hentaifoundry Ripper no longer errors out when there is no next page

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaifoundryRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/RedditRipper.java
- src/main/java/com/rarchives/ripme/utils/RipUtils.java
I added erome support to RipUtils.getFilesFromURL
> Reddit erome

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
The ripper no long gets the full sized image but instead gets the image from display_url in the json data
> IG ripper now uses display_url when downloading images

- src/main/java/com/rarchives/ripme/ripper/rippers/ImgurRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImgurRipperTest.java
The issue was caused by recognizing the link as SERIES_OF_IMAGES and failing to find comma in the link which resulted in throwing MalformedUrlException. At first I tried to tackle the problem by treating single image as an album with single image and trying to reuse ripAlbum method, however, I would need to add additional complexity by another if conditions in getImgurAlbum method, which I didn't like. I decided to  fix this issue by introducing new SINGLE__IMAGE type recognizable by another regex expression. and pass the logic to dedicated ripSingleImage method.
> Fixes #410 Imgur - Cannot download albums with a single image in

- src/main/java/com/rarchives/ripme/ripper/rippers/EroShareRipper.java
The ripper no longer adds an extra https: to links
> Fixed eroshae ripper

- src/main/java/com/rarchives/ripme/App.java
- src/main/java/com/rarchives/ripme/ripper/rippers/FacebookRipper.java
This adds changes the check for command-lines arguments to avoid throwing an error when no argument is passed on an headless system. It will instead gracefully show the help page to the user.
It also adds a check for the Mac OS-specific properties, to avoid setting them on other systems.
The OS-specific properties and the app initialization have been moved to after the isHeadless check for cleanliness (No need to set GUI properties on an headless app and no need to initialize if we're only going to show an help page).
> Improved handling of headless mode & OS-specific config

- src/main/java/com/rarchives/ripme/App.java
Fixes the case of using command-line on a non-headless system, where the GUI would open anyway.
> Fix usage of command-line on non-headless systems

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
The ripper now send the cookie ig_pr=1 when getting the next page
> InstagramRipper now send ig_pr=1 cookie when getting next page

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
The ripper can now generate the x-instagram-gis header and send it when ever we fetch a new page
> Ig nextpage fix

- src/main/java/com/rarchives/ripme/ripper/rippers/WebtoonsRipper.java
The regex now matches strings including _ and -
> Fix webtoons canRip regex

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
The ripper now requests the first 50 image instead of the first 100 mean ig no longer returns a 400 error
> Instagram ripper no longer throws a 400 error when getting new pages

- src/main/java/com/rarchives/ripme/ripper/rippers/Hentai2readRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/Hentai2readRipperTest.java
I changed the hentai2read regex
> Hentai2read test fixes

- src/main/java/com/rarchives/ripme/ripper/rippers/WordpressComicRipper.java
The ripper now sends the referrer header when downloading from tnbtu.com meaning images on that site no longer 404
> tnbtu ripper now sets referrer header

- src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java
Replacing `http` with `https` in an URL already starting with
`https://...` changes its scheme/protocol to `httpss`.
I've simply added a `:` to the replacement strings to prevent this from happening.
(My editor also removed some spaces from the end of some lines)
> [tumblr] avoid 'httpss' in image URLs

- src/main/java/com/rarchives/ripme/App.java
Sorry for my horrible Java skills, but this adds basic support for SOCKS v5 servers on CLI
> Added support for SOCKS v5 Server

- src/main/java/com/rarchives/ripme/ripper/rippers/WordpressComicRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/WordpressComicRipperTest.java
I addded a ripper for 8muses.download
> Wordpress 8muses.download

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaifoundryRipper.java
Hentai-Foundry, by default, filters quite a few images when looking at a user's gallery, but you can click the "Filters" button in the top-left of the page and adjust your filter settings.
This commit fills out and submits the filter settings form, allowing all content to be shown, before fetching the first page.
For comparison, the same thing is also implemented in my own project: https://github.com/mikf/gallery-dl/blob/a2020c736e8f947a7f44a5daf4cdfd598a29e17b/gallery_dl/extractor/hentaifoundry.py#L115-L145
As you can see, it is possible to get the YII_CSRF_TOKEN from your own cookies, but I didn't want to deal with string operations in Java ...
On another note: The very first request to just …
> [hentaifoundry] set content filter

- src/main/java/com/rarchives/ripme/ripper/rippers/HitomiRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HitomiRipperTest.java
I added a ripper for Hitomi.la
> Hitomi ripper

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/test/java/com/rarchives/ripme/tst/AbstractRipperTest.java
addURLToDownload no longer erroneously creates sub dirs if it can't get the extension of a file 
> Abstract ripper fixes

- src/main/java/com/rarchives/ripme/ripper/rippers/GfycatporntubeRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/GfycatporntubeRipperTest.java
Added a ripper and unit test for Gfycatporntube.com
> Added Gfycatporntube.com Ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/DynastyscansRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/DynastyscansRipperTest.java
I added a ripper for dynasty-scans.com
> Added ripper and unit test for dynasty-scans.com

- src/main/java/com/rarchives/ripme/ripper/rippers/SmuttyRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/SmuttyRipperTest.java
I rewrote the ripper to be use AbstractHTMLRipper, made getGID work with user pages and added a unit test
> Added user support for smutty.com

- src/main/java/com/rarchives/ripme/ripper/rippers/NudeGalsRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/NudeGalsRipperTest.java
> Fixed NudeGalsRipper

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ripper/AlbumRipper.java
- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
- src/main/java/com/rarchives/ripme/ripper/VideoRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/FivehundredpxRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/TsuminoRipper.java
When download files ripme can now set the file extension to the file MIME type (With "image/" stripped from it)
> addURLToDownload can now set the file extension to the files MIME type

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
I updated a regex so the ripper can find the query ID again
> Fixed queryId regex

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
I updated a regex so the ripper can find the query ID again
> Fixed instagram ripper regex

- src/main/java/com/rarchives/ripme/ripper/rippers/TsuminoRipper.java
> TsuminoRipper no longer requires album name to download

- src/main/java/com/rarchives/ripme/ripper/rippers/Hentai2readRipper.java
I changed how the ripper find the page with the comics thumbnails
> Fixed hentai2read ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
> EightmusesRipper now adds file extension to filename

- src/main/java/com/rarchives/ripme/ripper/rippers/Hentai2readRipper.java
I changed the select statement that the ripper uses to find the first page
> hentai2read can now get the album thumbnail link again

- src/main/java/com/rarchives/ripme/ripper/rippers/NhentaiRipper.java
- src/main/java/com/rarchives/ripme/utils/Utils.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/NhentaiRipperTest.java
The user can now add a comma separated list of tags in the config file with a key of "nhentai.blacklist.tags" and the ripper will skip any albums with those tags
I also added a way to get ConfigStringArrays from ripmes config file
Example: Adding "nhentai.blacklist.tags = one,two, three" will cause ripme to skip any nhentai album with the tags one, two or three
> Can now blacklist nhentai tags

- src/main/java/com/rarchives/ripme/ripper/rippers/Hentai2readRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/Hentai2readRipperTest.java
Added quick queue support for hentai2read
> Added quick queue support for hentai2read ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/SankakuComplexRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/SankakuComplexRipperTest.java
The ripper now gets posts from the subdomain of the entered url and no longer assumes the subdomain is chan
> SankakuComplexRipper can now download from different subdomains

- src/main/java/com/rarchives/ripme/ripper/rippers/BatoRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/BatoRipperTest.java
Added a ripper plus unit tests for bato.to
> Added ripper for bato.to

- src/main/java/com/rarchives/ripme/ripper/rippers/WordpressComicRipper.java
I added quick queue support for 8muses.download search pages and category pages
> Added quick queue support for 8muses.download

- src/main/java/com/rarchives/ripme/ripper/rippers/EHentaiRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/EhentaiRipperTest.java
The user can now add a comma separated list of tags in the config file with a key of "ehentai.blacklist.tags" and the ripper will skip any albums with those tags
I also added a way to get ConfigStringArrays from ripmes config file
Example: Adding "ehentai.blacklist.tags = one,two, three" will cause ripme to skip any ehentai album with the tags one, two or three
> Added the ability to blacklist tags on ehentai

- src/main/java/com/rarchives/ripme/ripper/AbstractJSONRipper.java
> Break if already downloaded x times

- src/main/java/com/rarchives/ripme/ripper/rippers/NhentaiRipper.java
I rewrote the ripper to get image links from thumbnails and added quickQueue support for tag pages
> Nhentai rewrite

- src/main/java/com/rarchives/ripme/ripper/rippers/MyhentaicomicsRipper.java
The ripper now requests the proper url and using https for all pages
> myhentaicomics ripper now requests proper url when downloading images

- src/main/java/com/rarchives/ripme/App.java
When ripping all urls in a file (Using the -f flag) ripme will now skip any line starting with // or #
> Can now include comments in url files

- src/main/java/com/rarchives/ripme/App.java
- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ripper/AlbumRipper.java
- src/main/java/com/rarchives/ripme/ripper/VideoRipper.java
- src/main/java/com/rarchives/ripme/ui/UpdateUtils.java
Changed try blocks that used streams and other classes that implement the Closeable, to try-with-resources statement, which implicitly close Closeables.
> Added try-with-resources blocks

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
if `Utils.getConfigBoolean("urls_only.save", false)` returns true `writeDownloadedURL` now just returns and doesn't write the downloaded url
> No longer writes url to url_history file is save urls only is checked

- src/main/java/com/rarchives/ripme/App.java
As documented in the wiki, the `-n, --no-prop-file` option should prevent the creation of the properties file, however, it has the opposite effect currently. I believe even with the changes in ef1cab6 the `rip.properties` file will still _never_ be created for people exclusively using the CLI unless this switch is set.
> Reverse -n, --no-prop-file behaviour

- src/main/java/com/rarchives/ripme/App.java
- src/main/java/com/rarchives/ripme/ripper/AbstractHTMLRipper.java
- src/main/java/com/rarchives/ripme/ripper/AbstractJSONRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/BcfakesRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/DrawcrowdRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/DribbbleRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/EHentaiRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/FivehundredpxRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/FlickrRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/FuraffinityRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/HentaifoundryRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/ImagevenueRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/ImgurRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/NfsfwRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/PhotobucketRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/PornhubRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/TwitterRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/TwodgalleriesRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/video/GfycatRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/video/MotherlessVideoRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/video/TwitchVideoRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/video/VidearnRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/video/VineRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/video/XhamsterRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/video/YoupornRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/video/YuvutuRipper.java
- src/main/java/com/rarchives/ripme/ui/MainWindow.java
- src/test/java/com/rarchives/ripme/tst/ui/RipStatusMessageTest.java
Replaced use of Collection.size () by Collection.isEmpty () which makes the code more readable and may have more performance
> Replaced use of Collection.size () by Collection.isEmpty ()

- src/main/resources/LabelsBundle_ru_RU.properties
> Russian translation

- ripme.json
Changed the value of currentHash in ripme.json to the sha256 hash of ripme.jar from the 1.7.50 release
> currentHash now matches the hash of ripme version 1.7.50

- src/main/java/com/rarchives/ripme/App.java
- src/main/java/com/rarchives/ripme/ui/MainWindow.java
- src/main/java/com/rarchives/ripme/ui/UpdateUtils.java
I added a -j flag that updates ripme
> Can now update ripme from the commandline

- src/main/java/com/rarchives/ripme/ripper/rippers/TheyiffgalleryRipper.java
The ripper now finds thumbs by grabbing all images in the "thumbnail" class
> Fixed TheyiffgalleryRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/AerisdiesRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/AerisdiesRipperTest.java
Changed how the ripper gets the album title and added more unit test
> Fixed Aerisdies ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/BatoRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/NhentaiRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/PichunterRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/Rule34Ripper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/WebtoonsRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/video/ViddmeRipper.java
Replaced use of Collection.size () by Collection.isEmpty () in ViddmeRipper.
Replaced the if-else statement by a single return statement.
> Replaced the if-else statement by a single return statement.

- src/main/java/com/rarchives/ripme/ripper/rippers/VscoRipper.java
Added support for vsco profiles
> Added the ability to rip from vsco profiles

- src/main/java/com/rarchives/ripme/ui/UpdateUtils.java
When updating ripme using the -j flag the changes since the last version of ripme will be printed on screen and cut down on repeated code by moving said code to the getChangeList func
You can now force ripme to update even if it's the latest version by setting the config key "testing.always_try_to_update" to true
You can now disable update hash checking by setting the config key "security.check_update_hash" to false
> Various update improvements

- src/main/java/com/rarchives/ripme/ripper/VideoRipper.java
- ordered imports alphabetically;
- removed signature of the canRip method, which is already in AbstractRipper;
- split variable declaration in different lines;
- corrected javadocs alignment;
- replaced unnecessary use of StringBuilder.
- added a few empty lines to increase the readability of the code
> Updating the VideoRipper class

- release.py
I wrote a script to automate new releases
> Releases are now automatic

- patch.py
patch.py now commits all changes it made
> patch.py now commits change to currentHash

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
I added is3.4chan.org to the list of 4chan domains and removed the code that would cause any url with '/thread/ or '/res/' in the title to be detected as chans
> 4chan new domain

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
Added 420chan, 7chan and xchan to chanRippers `canRip`
> Fixed failing tests on chanripper

- src/main/java/com/rarchives/ripme/ripper/rippers/E621Ripper.java
Tweaked how getGID works so it now accepts urls with order:Score at the end
> E621 ripper now accepts urls with order:Score at the end

- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/XhamsterRipperTest.java
The can rip now allows for a 2 letter country prefix before the xhamster url
> XhamsterRipper now accepts all countries subdomains

- src/main/java/com/rarchives/ripme/ripper/rippers/FuraffinityRipper.java
ripme now allows users to log in to FA using their own account cookies or to not log in at all if they're not ripping NSFW content
Ripme now also prints a warning about using the shared account when a user logs in using the shared account. I also fixed NSFW file downloading and now the ripper downloads fullsized images
> Users can now use their own account when ripping Furaffinity

- src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java
- src/main/java/com/rarchives/ripme/utils/RipUtils.java
As Deviantart now blocks automatic log in, I changed the ripper to use cookies dumped from a browser
TODO: Retest this in 3 days to see if the userinfo cookie has expired or not
> DeviantartRipper now logs in using cookies 

- src/main/java/com/rarchives/ripme/ripper/rippers/FuraffinityRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FuraffinityRipperTest.java
I made the ripper use RipUtils.getCookiesFromString when loading cookies and added a login unit test
>  Furaffinity ripper now uses RipUtils.getCookiesFromString to load cookies

- src/main/java/com/rarchives/ripme/ripper/rippers/TwitterRipper.java
The ripper now requests all of a users retweets as well as their tweets. The ripper now also downloads videos in the largest size possible
> Twitter ripper now rips retweets

- patch.py
patch.py now reminds users to push to master before running release.py
> patch.py now reminds users to run git push before release.py

- src/main/java/com/rarchives/ripme/ripper/rippers/RedditRipper.java
- src/main/java/com/rarchives/ripme/utils/RipUtils.java
The reddit ripper can now rip v.redd.it videos
> Reddit ripper can now rip videos from v.redd.it

- src/main/java/com/rarchives/ripme/ripper/rippers/ZizkiRipper.java
The ripper now uses the h1 element to get the album title
> Fixed ZikiRipper getAlbumTitle

- src/main/java/com/rarchives/ripme/ripper/rippers/PicstatioRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/PicstatioRipperTest.java
Added support for picstatio.com
> Picstatio ripper

- src/main/java/com/rarchives/ripme/ripper/AbstractJSONRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
I changed AbstractJSONRipper to respect hasASAPRipping and fixed the instagram ripper
> Got InstagramRipper working again 

- src/main/java/com/rarchives/ripme/ripper/rippers/TwitterRipper.java
This fixes a bug introduced in 1.7.53 which caused some twitter videos not to download
> Twitter ripper no longer errors out on some videos

- src/main/java/com/rarchives/ripme/ripper/rippers/ArtStationRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ArtStationRipperTest.java
Add ripping support for ArtStation projects (e.g. [arstation.com/artwork/projectid]()) and user profiles (e.g. [artstation.com/username]()). Some remarks: 
* It doesn't work on ArtStation-hosted user websites such as [username.artstation.com]() (there's no JSON to retrieve in the page source, it would require a new ripper based on HTML to support those)
* It can't rip external content that isn't hosted on ArtStation such as videos, 3D models, etc (those contents are hosted in other websites and shown on ArtStation through embedded iframes) 
> ArtStation ripper

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/BcfakesRipperTest.java
I disabled the sites unit test as it has been down for 4+ days
> Disabled test for Bcfakes.com as the site has been down for many days

- release.py
Fix handling of files that are not in sub-dirs.
Use raw strings for regex, won't change anything as `\d` is not an escape sequence. However it is still good practice.
Should fix #672.
> release.py | Fix handling of files that are not in subdirs, and other minor changes.

- release.py
Small quality of life fix to make the script more portable (Mac and Linux). Now one can type `./release.py [ARGS...]` instead of specifying `python3`.
> Fix shebang for release.py and make it executable

- src/main/java/com/rarchives/ripme/ripper/rippers/EromeRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/EromeRipperTest.java
I fixed the ripper and added quickQueue support for profile pages
> Fixed erome ripper and added quickQueue support

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MyhentaicomicsRipperTest.java
I added 2 new unit tests for myhentaicomics.com that cover the quickQueue features
> Added unit test for Myhentaicomics quickQueue

- src/main/java/com/rarchives/ripme/ripper/rippers/ModelmayhemRipper.java
The ripper now sets the worksafe cookie to 0 when making requests, so the site returns the nsfw version
> ModelmayhemRipper can now donwload nsfw images again

- src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/DeviantartRipperTest.java
Changed how the ripper gets the galleryID and the username
> Got DeviantartRipper working again

- src/main/java/com/rarchives/ripme/ripper/rippers/TwitterRipper.java
Tweets larger than 140 characters are Extended Tweets. When those Tweets are served by the standard REST API in the default compatibility mode the media is left out. Using `tweet_mode=extended` gets all of the media.
Example: https://twitter.com/BlackChono (NSFW). 1.7.56 downloads only 113 images, and this PR 174.
> Fix Twitter. Get images from Extended Tweets

- src/main/java/com/rarchives/ripme/ui/MainWindow.java
- src/main/resources/LabelsBundle_nl_NL.properties
Added the Dutch translations by @nfrelink
> Added nl_NL translation

- src/main/java/com/rarchives/ripme/ripper/rippers/TwitterRipper.java
This undoes a change I made to try and get the twitter ripper to rip all tweets, the change was ineffective. 
> Twitter ripper no longer rips retweets by default

- src/main/java/com/rarchives/ripme/ripper/rippers/HitomiRipper.java
> fixed HitomiRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java
Added support for downloading from all galleries and sub galleries. 
> DA ripper fixes

- src/main/java/com/rarchives/ripme/ui/UpdateUtils.java
the update Confirm Dialog now uses string.format instead of just +ing a bunch of strings and change list now has all new lines removed
> Fixed update box formating

- src/main/java/com/rarchives/ripme/ripper/rippers/ManganeloRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ManganeloRipperTest.java
Fixed the ripper, added another unit test
> Manganelo ripper fixes

- src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java
Now checks that a link starts with http before trying to download it
> Fixed minor bug with DeviantartRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/ImagearnRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImagearnRipperTest.java
Readded Imagearn ripper and unittest
> Readded Imagearn ripper and test

- src/main/java/com/rarchives/ripme/ripper/rippers/EromeRipper.java
Changed the getGID regex to match video urls
> Fixed erome video downloading

- src/main/java/com/rarchives/ripme/ripper/rippers/ManganeloRipper.java
No longer adds extra "https:" to links
> Fixed ManganeloRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
Added Desuarchive.org to chanrippers canRip
> Added support for Desuarchive.org

- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
> Fixed xhamster getNextPage

- src/main/java/com/rarchives/ripme/utils/RipUtils.java
getFilesFromURL can now get imgur mp4s
> getFilesFromURL now handles imgur gifvs

- src/main/java/com/rarchives/ripme/ripper/rippers/ArtStationRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ArtStationRipperTest.java
This PR fixes issue #776 by properly handling user profiles with more than 50 published projects. It also fixes an off-by-one bug which I still not sure how I didn't catch in the initial implementation (basically it would skip the first project of every user profile)
> ArtStationRipper: fix ripping from user profiles which many projects

- src/main/java/com/rarchives/ripme/ripper/rippers/LoveromRipper.java
The ripper now adds the "7z" extension to files
> loveroms ripper now properly names files

- src/main/java/com/rarchives/ripme/ripper/rippers/JabArchivesRipper.java
This adds a ripper for jabarchives.com. This currently only supports ripping bottom-level folders. If a folder you rip contains another folder, that subfolder will not be fully ripped, only the source image from its thumbnail will be included in the rip.
> Adding Jab Archives ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
Ripper now uses the obfuscated json data to get all image urls for each album.  
> Fixed EightmusesRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/CheveretoRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/CheveretoRipperTest.java
Added kenzato.uk to explicit_domains
> Added kenzato.uk to CheveretoRippers

- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
Now sets connection timeout and read timeout 
> Timeout now applies to both connection and read

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
Added 8chan url support again by whitelisting "8ch.net" domain while it has "/res/" in the url.
> Re-recognize 8Chan URLs

- src/main/java/com/rarchives/ripme/ripper/rippers/JabArchivesRipper.java
> JabArchivesRipper now allows for www. to appear in url

- .gitignore
- src/main/java/com/rarchives/ripme/ui/MainWindow.java
- src/main/resources/LabelsBundle_pt_BR.properties
Included a new bundle for pt_BR translations.
Altered .gitignore to negate *.properties rule for the i18n bundle resources. (why are the .properties files being ignored anyway?)
> Brazilian Portuguese (pt_BR) translation added

- src/main/java/com/rarchives/ripme/ripper/rippers/HqpornerRipper.java
Added a ripper for hqporner.com
> Added ripper for hdporner

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/PichunterRipperTest.java
Commented out a unit test that was failing randomly due to issues with pichunter.com 
> Removed flaky unittest for PichunterRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
Code that no longer works has been removed from the InstagramRipper.java.
> Obsolete code removed from InstagramRipper.java

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaiimageRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentaiimageRipperTest.java
Added ripper and unittest for hentai-image.com and hentai-comic.com
> Hentai image

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HqpornerRipperTest.java
Ripme now doesn't download the entire file during testing if the file is over 10 mb. I also added a unit test for hqporner 
> Test fixes

- pom.xml
- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ui/MainWindow.java
Extraordinarily long URLs can cause the log window to expand with them. Implemented wraparound to combat this. Also truncated the status label since it was affected as well.
For the log window, I did change the font to a mono-spaced font because the sans-serif font on my system caused the wraparound to behave strangely.
I did also, while scanning some of the code at first, change "flase" to "false" in a few comments.
> Fix #789: Implemented wraparound for log window and status label

- src/main/java/com/rarchives/ripme/ripper/rippers/RedditRipper.java
I added the `reddit.use_sub_dirs` config option which if false causes the reddit ripper to not use sub dirs
> Added config option to allow for using subdirs with the reddit ripper

- src/main/java/com/rarchives/ripme/ui/MainWindow.java
Added the ability to rip a range of urls. Example: entering "http://test.tld/test={1-10}" will rip http://test.tld/test=1, http://test.tld/test=2 ect
> Added ability to download range of urls

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ui/MainWindow.java
Reverts RipMeApp/ripme#805
I'm reverting this PR as it interdocued a few new bugs (Such as #880) and didn't wrap all text. These issues should be fixed and the PR should be remerged
> Revert "Fix #789: Implemented wraparound for log window and status label"

- src/main/java/com/rarchives/ripme/App.java
- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
Add the -a flag for appending a string to the rip folder name
> Added flag for appending a string to folder name

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MotherlessRipperTest.java
Replaced the dead unit test link with a working one
> Replaced motherless unittest

- src/main/java/com/rarchives/ripme/utils/RipUtils.java
getFilesFromURL now can handle imgur videos
> getFilesFromURL now can handle imgur videos

- src/main/java/com/rarchives/ripme/ui/MainWindow.java
URL range ripping now appendsLog when it runs into an error instead of just writing to the non-gui log
> URL range ripping now appendsLog when it runs into an error

- src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java
Removed option to download raw images from tumblr as tumblr now returns 403 for these images
> Removed option to download raw images from tumblr

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
Now uses /fl/ image url instead of /fm/
> 8muses ripper now gets full sized images

- README.md
Added a line about ripmes url range downloading
> Added url range downloading to list of ripmes features

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/LusciousRipperTest.java
Added a unit test for LusciousRipper
> Added unit test for LusciousRipper

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/SpankBangRipperTest.java
The flaky spankbang unit test now only runs if the config option `test.run_flaky_tests` is set to true. This will stop the test from running on travis (Where it always fails for some reason) but allow it to rub locally (where it passes)
> Made the SpankBangRipperTest only run locally and not in the CI

- src/main/java/com/rarchives/ripme/ripper/rippers/JagodibujaRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/JagodibujaRipperTest.java
Added a unit test for Jagodibuja ripper and added a stop check to the ripper so that it stops gathering urls when stopcheck() throws an IOException
> Added Jagodibuja ripper test

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/PahealRipperTest.java
Added a unit test for the PahealRipper
> Added a test for the PahealRipper

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImgurRipperTest.java
Added a unit test for getting a video from imgur using RipUtils.getFilesFromURL
> Added unit test for imgur videoes

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/TsuminoRipperTest.java
Added a unit test for TsuminoRipper
> Added unit test for TsuminoRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/HbrowseRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HbrowseRipperTest.java
Fixed the Hbrowse ripper and added a unit test
> Hbrowse ripper test

- src/main/java/com/rarchives/ripme/ripper/rippers/TsuminoRipper.java
- src/main/java/com/rarchives/ripme/utils/RipUtils.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/TsuminoRipperTest.java
Added the ability to blacklist tags on Tsumino 
> Tsumino tag black listing

- src/main/java/com/rarchives/ripme/ripper/rippers/EHentaiRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/NhentaiRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/EhentaiRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/NhentaiRipperTest.java
I refactored how tag blacklisting is done to cut down on repeat code 
> Tag black list refactoring

- src/main/java/com/rarchives/ripme/ripper/rippers/Tubex6Ripper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/Tubex6RipperTest.java
New ripper and unit test for Tubex6.com.  Builds and tests clean locally.
> Ripper and Unit test for Tubex6.com.  Closes digitalnoise/ripme#1

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/XhamsterRipperTest.java
Added a unit test covering getNextPage to the xhamster ripper
> Added getNextPage unit test for xhamster ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/RulePornRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/RulePornRipperTest.java
Ripper and Unit test for RulePorn.com.  Builds and test clean locally.
> Ruleporn.com Ripper (NSFW)

- src/main/java/com/rarchives/ripme/ripper/rippers/MyhentaigalleryRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MyhentaigalleryRipperTest.java
Added a ripper and unit test for myhentaigallery.com
> Myhentaigallery ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/EightmusesRipperTest.java
Fix getSubDir so it no longer adds 2 extra dashes to comic issues 
> Fixed EightmusesRipper so titles on disk no longer include ---

- src/main/java/com/rarchives/ripme/ripper/rippers/EromeRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/EromeRipperTest.java
The ripper now grabs both HD and SD video, replace 404ing url 
> Erome Fixes

- src/main/java/com/rarchives/ripme/ripper/rippers/SpankbangRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/SpankBangRipperTest.java
Rewrote the ripper so it now use AbstractSingleFileRipper instead of VideoRipper
> Ported the SpankBangRipper to AbstractSingleFileRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/MulemaxRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MulemaxRipperTest.java
Ported the MulemaxRipper to AbstractSingleFileRipper
> Port MulemaxRipper to AbstractSingleFileRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/TumblrRipperTest.java
Added support for ripping tumblr posts with embedded images and reenabled tumblr ripper unit tests
> Tumblr embedded image support

- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/XhamsterRipperTest.java
Readded video ripping support to the xhamster ripper
> Xhamster video

- src/main/java/com/rarchives/ripme/ripper/rippers/PorncomixDotOneRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/PorncomixDotOneRipperTest.java
Added a ripper for porncomix.one
> Porncomix.one Ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
> Added yuki.la to chan ripper

- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/XhamsterRipperTest.java
The ripper now visits each page to get the full sized image
> Fixed xhamster ripper

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HqpornerRipperTest.java
hqporner test now only runs is test.run_flaky_tests is true
> Marked HqpornerRipperTest as flaky

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
> Added support for 55chan.org

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/ripperhelpers/ChanSite.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ChanRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/RippersTest.java
I cleaned up the chan ripper, removed a ton of unneeded if statements and removed code for some now dead chans
I also added a testChanRipper function to RippersTest for testing chan rippers (So the test won't be marked as a failure if any links 404) and added a unit test for desuarchive.org
> Cleaned up chan ripper and removed dead chans

- README.md
Removed mention of tumblr full size image downloading
> Removed deature which is no longer in ripme from readme

- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
- src/main/java/com/rarchives/ripme/ripper/rippers/RedditRipper.java
If when creating a fileOutputStream ripme gets a "File name too long" error ripme will now shorten the file name to just under 255 bytes (The max file name length for ext file systems). 
This is a bit hackish ~~and assumes that the user is on Linux, with an Ext3 or 4 file system and is using UTF-8 encodings, if any of these things aren't true then the user will likely run into a File name too long even with these changes~~
After a bit of reading it looks like this should work on Windows as well
> Handle File name too long file system errors

- src/main/java/com/rarchives/ripme/ripper/rippers/TsuminoRipper.java
Changed a post request to a get request
> TsuminoRipper can download albums again

- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
Moved an if statement outside of the download loop so it's only run once instead of for ever few kilobytes of the downloaded file 
> Moved if statement outide of loop

- src/main/java/com/rarchives/ripme/ripper/rippers/E621Ripper.java
Previous version was only pulling sample images, and ignoring any videos or flash files. Now it looks for a video, then a flash, then the image link, as pulled from the fullsize link in the sidebar.
> Update e621 ripper to pull videos, flash files, and fullsize images

- pom.xml
Upgraded org.apache.httpcomponents to 4.3.6 so we're not longer vulnerable to CVE-2015-5262
> Upgraded org.apache.httpcomponents to 4.3.6

- src/main/java/com/rarchives/ripme/ripper/rippers/MangadexRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MangadexRipperTest.java
A ripper for Mangadex.org. Currently only chapters are supported
> Added ripper for Mangadex.org

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/TsuminoRipperTest.java
Switched out the 404 url with a new url
> Fixed Tsumino ripper unit test

- src/main/java/com/rarchives/ripme/ripper/rippers/DuckmoviesRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/DuckmoviesRipperTest.java
Added a ripper that supports 
https://vidporntube.fun/
https://pornbj.fun/
https://iwantporn.fun/
https://neoporn.fun/
https://yayporn.fun/
https://freshporn.co/
https://palapaja.stream/
https://freshporn.co/
https://pornvidx.fun/
https://palapaja.com/
Which all seem to be front ends for the same site
> Duckmovies frontend ripper

- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
- src/main/java/com/rarchives/ripme/ripper/rippers/RedditRipper.java
- src/main/java/com/rarchives/ripme/utils/Utils.java
- src/test/java/com/rarchives/ripme/tst/UtilsTest.java
I fixed 3 bugs where causing freezes (the bugs where ripme trying to download a null url, ripme trying to make a file with illegal chars in the name and ripme trying to make a file path longer than 260 char on windows)
> Ripme no longer freezes when ripping from reddit

- src/main/java/com/rarchives/ripme/ripper/rippers/SinnercomicsRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/SinnercomicsRipperTest.java
I added two new rip modes to the Sinnercomics ripper: pinup ripping (for a single image) and homepage ripping to rip all pinups.
(I modified the relevant test)
> Added pinups and homepage to Sinner Comics ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/MangadexRipper.java
Now downloads image from the cdns
> Fixed mangadex ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/HqpornerRipper.java
The hqporner ripper can now rip video hosted on mydaddy.cc and flyflv.com
> Added support for hqporner videos hosted on flyflv

- src/main/java/com/rarchives/ripme/ripper/rippers/FlickrRipper.java
Got working on the flickr ripper and it can now rip single page photo sets 
TODO before merge
> Flickr ripper can now rip from photo sets

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
Added the 4channel.org domain since 4Chan is moving its SFW boards to it.
"Attention: All work safe boards are soon going to be on the 4channel.org domain."
> Added 4Channel.org for SFW 4Chan Boards

- src/main/java/com/rarchives/ripme/ripper/rippers/FlickrRipper.java
Added the two unsupported symbols to the regex.
I didn't, but I noticed the relevant test was still disabled and re-enabled it. I didn't add this change since you closed #243 just recently and I don't know if it's intentional.
> Update userRegex, fixes #1063

- src/main/java/com/rarchives/ripme/ripper/rippers/DerpiRipper.java
This adds support for derpibooru.org
it also adds the config parameter `derpi.key` which is a string, you can set it to your account key and then it can rip more stuffs
> add derpi ripper

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java
- src/main/java/com/rarchives/ripme/ui/MainWindow.java
- src/main/java/com/rarchives/ripme/ui/RipStatusMessage.java
Fixed problem with showing message when ripping album or user which does not exist.
> Fixed issue #968

- src/main/java/com/rarchives/ripme/ripper/rippers/PhotobucketRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/PhotobucketRipperTest.java
Also make getFirstPage() public, if getNextPage() already is
(and it is used in the commented-out unit test).
Also minor style fixes.
Fixed #1067 caused by not passing referrer and cookies to addURLToDownload() method.
Also some other (mostly style) fixes.
- Well... TubeX6Ripper did fail both in the CI build and when running `mvn test` locally. I haven't found an issue about it, but as it is completely independent from Photobucket ripper, it's probably unrelated to these changes.
- The whole unit test for Photobucket ripper was uncommented when running `mvn test` locally. It was  successful.
> Fix issue with Photobucket downloads containing watermark.

- src/main/java/com/rarchives/ripme/ui/UpdateUtils.java
The relevant code was changed back in #1032 (de773db4f4c60c85c4b54fe70c2ed996f3999a83) but the import line still remained in the code.
By removing that line I was able to compile with Java 11.
```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ripme:
Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed:
The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ripme:
Execution default-test of goal …
```
> Remove HexBinaryAdapter import remnant.

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaiCafeRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentaicafeRipperTest.java
Ripper now can handle urls with line breaks in them
> Hentaicafefixes

- src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java
The ripper now respects download.save_order and can rip from liked pages (USERNAME.tumblr.com/likes, https://www.tumblr.com/liked/by/USERNAME)
> Added support for tumblr like pages; now respects download.save_order

- src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java
Turns out that the tumblr ripper returns item out of order which makes it a pain to download comics from from tags. This PR fixes that by putting the date in the image name when ripping from tags 
> Tumblr ripper now puts date in name of files when ripping from tags

- src/main/java/com/rarchives/ripme/ripper/rippers/XcartxRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/XcartxRipperTest.java
Added a ripper and unit test for Xcartx.com
> Added a ripper for Xcartx.com

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaifoundryRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentaifoundryRipperTest.java
Added the ability to rip pdfs from hentai foundry 
> Added support for Hentai foundry stories

- src/main/java/com/rarchives/ripme/ripper/rippers/EromeRipper.java
- src/main/java/com/rarchives/ripme/ui/MainWindow.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/EromeRipperTest.java
Minor changes to EromeRipper which would capture blank image urls before, now captures required image urls (if present).
Added a test to verify the above change.
> Fixed EromeRipper and added new test to EromerRipperTest.

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaidudeRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentaidudeRipperTest.java
> Added support for Hentaidude.com

- src/main/java/com/rarchives/ripme/ui/UpdateUtils.java
Fixed the update dialog from going out of screen( by using a JEditorPane of fixed size) and made it scrollable( by wrapping the JEditorPane inside a JScrollPane).
> Fixed update dialog going out of screen.

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ripper/AlbumRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/RedditRipper.java
Added a check so albumRipper doesn't download already downloaded files 
> Started on fixing reddit redownloading issue [WIP]

- src/main/java/com/rarchives/ripme/ripper/rippers/EHentaiRipper.java
Fixed the e-hentai getGID regex so it no longer requires the url to end in /
> Fix e-hentai regex

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentaiimageRipperTest.java
The hentaiimage unit test kept failing on the CI server despite working locally so the test was marked as flaky 
> Mark hentaiImage test as flaky

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaifoundryRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentaifoundryRipperTest.java
Add an else block to an if so files wouldn't be added to the download queue twice 
I also fixed the getGID and added a unit test for it
> Added an else block so the pdf download unit test wouldn't fail

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/VideoRippersTest.java
Disabled a unit test for a failing ripper
> Disbaled failing test for pornhub

- src/main/java/com/rarchives/ripme/ripper/rippers/JabArchivesRipper.java
This will now include the image title in the saved filename when writing
the final text files, which fixes duplicate files and naming conflicts from
downloading the same gallery multiple times.
> Updating Jab Archives ripper to add image title

- src/main/java/com/rarchives/ripme/ui/UpdateUtils.java
This fixes the download box displaying only one line for all versions
and their fix descriptsion out of ripme.json.
> replaceAll takes a regex, escape newline to replace it with <br>

- src/main/java/com/rarchives/ripme/ripper/rippers/BatoRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/FuraffinityRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/HitomiRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/ZizkiRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ChanRipperTest.java
* [] a bug fix (Fix #...)
Cut down on some unneeded logging so the unit test log is less cluttered 
> Reduce log spam

- src/main/java/com/rarchives/ripme/ui/MainWindow.java
Trim the line input to avoid problems with whitespace on each line.
Regarding the Download URL List functionality:
Properly handle the closing of a BufferedReader by using a Try with Resources, as it stands it is not closed. And trim each line of the input to avoid white-space issues.
Tested with a text file with these contents:
```
https://www.reddit.com/r/18_19/
https://www.reddit.com/r/60fpsporn/
...
// Users
https://www.reddit.com/user/AliceNice          			     
https://www.reddit.com/user/BambooFever			   		 	
...
```
> [Bugfix] Handle a resource with a proper Try with Resources.

- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
- src/main/java/com/rarchives/ripme/ripper/rippers/HqpornerRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HqpornerRipperTest.java
- Updated ripper to support actress/category/studio/top links.
- Ripper initially supported video download from only two hosts( flyflv and mydaddy). Added a generic downloader( getVideoFromUnknown()) to download from other hosts( like hqwo).
- Added next page support.
> Updated hqporner to support actress/category/studio/top links.

- src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java
The DA ripper now takes favorite galleries 
> DA ripper now takes fav urls again

- src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java
Now adds _1280 to all images in order to rip highest quality available, as explained in #974
> Tumblr ripper downloads highest quality available

- src/main/java/com/rarchives/ripme/ripper/rippers/LusciousRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/LusciousRipperTest.java
Improved luscious ripper for faster multi threaded download.
- `getURLsFromPage()` now returns all the image urls from the page( unlike the previous implementation which returned the download url of the single image).
- `getNextPage()` now returns the next page of the album( Previous implementation returned next image url).
- `getGID()` now accepts 2 url formats, `luscious.net/albums/albumname`  and `members.luscious.net/albums/albumname`
- Added `LusciousDownloadThread` to download images/ videos from image urls with high retry count( to counter read timeout).
For issue #404 and issue #977 with `remember.url_history =  true` and `
file.overwrite = …
> Improved luscious ripper fixed incomplete albums ripping.

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaidudeRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/MyhentaigalleryRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HqpornerRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ModelxRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MyhentaigalleryRipperTest.java
> Fixed some travis build failures.

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/PornhubRipperTest.java
Marked the pornhub album test as flaky 
> Marked pornhub album test as flaky

- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
Adds xhamster.one url to canRip function and rewrites url to xhamster.com.
> xHamster New URL Fix

- src/main/java/com/rarchives/ripme/ripper/rippers/FuraffinityRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FuraffinityRipperTest.java
Hi, i saw that furaffinity ripper was only able to download https://www.furaffinity.net/gallery
I have add the posibility to donwload  https://www.furaffinity.net/scraps. I had seen a issue posted like 13 days ago, but now seems is deleted.
I have add a getGid Pattern  to scraps. 
I have add a unitTest to check that works correctly.
* [x ] Downloads all relevant content.
Sorry for my english and if something related to a good pull request is not good enough. It's my first pull request on github.
> Changes furaffinityRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/RedditRipper.java
- src/main/resources/rip.properties
Adds support for filtering out post/comments outside of a specific score range from being downloaded. Examples with comments placed in the rip.properties file. Also added some (incomplete, but some is better than none) docs to the RedditRipper
Couldn't see a way to test a class with varying entries in the .properties file. If anyone can point me in the right direction I'll be happy to get on that.
> Closes #1143 Added support for score filtering when ripping from reddit

- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImagevenueRipperTest.java
Disabled a failed unit test. The test should be fixed and reenabled 
> Disabled failing Imagevenue Ripper Test

- src/main/java/com/rarchives/ripme/ripper/rippers/GfycatRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/XcartxRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/XlecxRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/XlecxRipperTest.java
Added a ripper for xlecx.com.
As **xlecx** is a clone of **xcartx**, XlecxRipper extends from XcartxRipper with some minor changes.
> Added Ripper for Xlecx

- src/main/java/com/rarchives/ripme/ripper/rippers/PorncomixDotOneRipper.java
Fixed the porncomix.one ripper
> Fixed porncomix.one ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/FuskatorRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FuskatorRipperTest.java
* FuskatorRipper failed to rip images due to changes in the website. Fixed by minor changes in the `getURLsFromPage()` method.
`getURLsFromPage()` method now sends a GET request to receive a JSONObject and retun image urls from it.
* FuskatorRipperTest has been un-commented to check if its still failing in travis-ci (#393 )
> Fixed FuskatorRipper not ripping images.

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
addURLToDownload now checks if the url has spaces in it and if so replaces them with %20
> Now handles urls with spaces in them

- ripme.json
Fix an oversight or mistake in writing or automated creation of the changelog. I didn't do any testing because it's such a minor change unrelated to the actual functionality I doubt it'd affect anything in the the program. Also GitHub's editor put the blank ending line automatically.
> Remove additional space character in ripme.json

- patch.py
Patch.py now removes any leading spaces from commit messages. 
> Patch.py now removes any leading spaces from commit message

- src/main/java/com/rarchives/ripme/ripper/AbstractHTMLRipper.java
- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
> some more checks to avoid downloading invaild urls 

- src/main/java/com/rarchives/ripme/ripper/rippers/ArtstnRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ArtstnRipperTest.java
* Added support for artstn.co, short urls  for Artstation.
`ArtstnRipper` extends `ArtStationRipper` with minor changes.
> Added support for artstn.co

- src/main/java/com/rarchives/ripme/ripper/rippers/TwitterRipper.java
- src/main/resources/rip.properties
* Added a boolean  config option `twitter.rip_retweets` in rip.properties. The default value is set to `true` as not to change the behaviour of the TwitterRipper unless needed.
* TwitterRipper does not use the `include_rts` parameter, instead uses the `retweeted_status` attribute for the `tweet object`. 
API description for `retweeted_status` :
`Retweets can be distinguished from typical Tweets by the existence of a retweeted_status attribute. This attribute contains a representation of the original Tweet that was retweeted.`
* Minor changes were required in `parseTweet()` and `RIP_RETWEETS` constant in TwitterRipper.
> Added support for optional retweet downloads.

- src/main/java/com/rarchives/ripme/ripper/rippers/MulemaxRipper.java
The ripper now sends the referrer when requesting a video, which causes the site to not throw a 403 error
> Fixed MulemaxRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaifoundryRipper.java
The ripper now use https when making requests to the site.
There also is now a config option "hentai-foundry.filter_order" which controls the sorting for ripping hentai foundry. The new default is date_old which causes the pages to downloaded in the order they were uploaded
Possible values are "date_old" and "date_new"
> Hentai foundry sort now has a config option; HF ripper now uses https

- src/main/java/com/rarchives/ripme/ripper/rippers/ThechiveRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ThechiveRipperTest.java
* Added support for `i.thechive.com/someUserName`
* Fixed `thechive.com/YEAR/MONTH/DAY/POSTTITLE/` ripper which was not working due to website changes.
* Fixed `ThechiveRipperTest` as the previous test would not run due to bad name.
* Added test for `i.thechive.com/someUserName` and gifs- url.
> Fixed ThechiveRipper( and added support for i.thechive.com)

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
Fixed bug that caused ripme to request files multiple times per 8muses rip 
> 8muses ripper no longer makes unneeded requests

- src/main/java/com/rarchives/ripme/ripper/rippers/EromeRipper.java
Now supports pages like https://www.erome.com/onlybestones?page=2
> Erome ripper supports pages

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaifoxRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentaifoxRipperTest.java
> Added support for Hentaifox.com

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/ripperhelpers/ChanSite.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ChanRipperTest.java
Users can now add new chan sites to ripme by editing/adding the chans.chan_sites config value.
The format for this value is "site.domain([sitecdn.domain|sitecdn2.domain})"
Examples
For 4chan you'd add "boards.4chan.org[4cdn.org|is.4chan.org|is2.4chan.org|is3.4chan.org]"
For desuchan you'd add "desuchan.net" leaving out the [] because desuchan.net doesn't have any cdn domains
To add both 4chan and desuchan.net you'd add "boards.4chan.org[4cdn.org|is.4chan.org|is2.4chan.org|is3.4chan.org],desuchan.net"
This PR is currently lacking a unit test, which it needs before it can be merged
> Users can now add chan site by adding a line in the config

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
Now instead of having to remember the order of params for addURLToDownload you can just pass a map. Hopefully this will make using addURLToDownload less frustrating 
I used `getOrDefault` so you'd only have to add the params you'd care about and the rest will be sane default values (So no more trying to remember what those sane defaults are when calling addURLToDownload)
Options are getFileExtFromMIME, prefix, subdirectory, referrer, fileName, extension and getFileExtFromMIME.
getFileExtFromMIME should have a value of "true" if you want it to get the file ext from MIME type
Example 
```
Map<String, String> data = new HashMap<String, String>();
data.put("referrer", "example.tld"); …
```
> Can now pass a map of params to addURLToDownload

- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/ErofusRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ErofusRipperTest.java
Adds basic support for erofus.com
> Added ripper for Erofus.com

- src/main/java/com/rarchives/ripme/ripper/rippers/FuskatorRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FuskatorRipperTest.java
FuskatorRipper was unable to rip images from links containing `~` (Issue #1261 )
> Fixed FuskatorRipper not ripping some images.

- src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
I added a check to a loop that causes the loop to only run once when tests are running
> EightmusesRipper no longer spams log

- src/main/java/com/rarchives/ripme/ripper/rippers/GfycatRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/GfycatRipperTest.java
gfycat ripper can now rip from profiles
> Added support for Gfycat profiles

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaifoundryRipper.java
Added an option to disable file prefix for hentai foundry albums 
> Added opt to disable prefix for HentaifoundryRipper

- src/main/java/com/rarchives/ripme/ui/UpdateUtils.java
Downloads update to the same path as the jar being updated
> Updater no longer always saves the update to the users home dir on linux

- src/main/java/com/rarchives/ripme/ripper/rippers/ComicextraRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ComicextraRipperTest.java
* Added new ripper for `comicextra.com`
* Supports ripping of whole comic( all chapters) or individual chapter of a comic.
* Each chapter is saved in a subdirectory, named as `chapter-1`, `chapter-full` etc.
* Each image is named as `page` as the original file names are very long ( and garbled). 
ex: `001_page.jpeg`, `027_page.jpeg` etc.
> Added ripper for comicextra.com

- src/main/java/com/rarchives/ripme/ripper/rippers/ArtStationRipper.java
* Artstation ripper would error out with status code 403. This is caused due to cloudflare.
* Added a `getJson(url)` method to fix the above issue.
* Replaced all the calls to `Http.get(url).getJSON()` with the above method.
> Fixed artstation ripper not ripping images.

- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
Fixes issue with page number in photos URL.
Added regex for handling page numbers in photos URL.
> Fixes #1276

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
The `rhx_gis` variable was removed by Instagram. It seems like we can still fetch pages without it, so we ignore the error and set `rhx_gis` to an empty string.
I tried re-ripping multible accounts that were downloaded using the previous version, and all files were downloaded and are the same, so I assume that it should work for all accounts & post links.
If needed, the variable could also be removed from the ripper (since it no longer serves any purpose).
> Fix Instagram ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java
Fixes for https://github.com/RipMeApp/ripme/issues/1303
Gallery/Favourites URL without trailing / works now.
Added some failsaves to prevent 404's with the image galleries mentioned in the issue above.
Changed the login. It actually works now.
Added some documentation
Tested with URLS mentioned in Javadoc.
> Fixes for Deviantart Ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
Instagram ripper should always honor the instagram.download_images_only property and there were many places that did not look at this property before starting downloads.
I made a few additional changes to make it easier to control how downloads are started. There were too many places starting downloads bypassing the setting / property. Also this is my first contribution to an open project, apologies if something is not correct in the PR.
> Instagram fix for ignoring download_images_only. Issue #1284.

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
Instagram ripper can now extract qhash again 
> quick dirty fix for instagram ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/MeituriRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MeituriRipperTest.java
I made a new ripper for Meituri.com (mostly a non-nude Asian modelling photography website). It is somewhat of a port of [my own Python code](https://github.com/kittenparry/meituri-downloader) but better because in my Python code you need to enter the number of images and album ID manually whereas you only paste in the URL of the page in this version.
> Added Meituri Ripper [NSFW]

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/InstagramRipperTest.java
Fixed tag ripping.
Added support for TAGGED, IGTV, STORIES, PINNED items.
'sessionid' cookie support for stories and private rips.
> Instagram ripper renewed

- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
Modified the URL patterns to recognize users videos page items and queue them up appropriately.  Also updated the sanitize URL function to be more efficient and explicit in modifications.
> Xhamster video queue

- src/main/java/com/rarchives/ripme/App.java
Fix history when rip using -u
Fix history load when using -r. Now it's load from history.json instead of rip.properties
> Fix history when rip using -u

- src/main/java/com/rarchives/ripme/App.java
- src/main/java/com/rarchives/ripme/utils/Utils.java
Added ability to set history filename and path on the CLI using -H or --history. Defaults to the usual url_history.txt file.
> Adding support for CLI option to change history file path.

- src/main/resources/log4j.file.properties
Change Threshold of console appender when Save Logs is on (Using log4j.file.properties instead of log4j.properties)
> Fix CLI displays no infomation if "save logs" is checked

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ChanRipperTest.java
Add thebarchive.com, archiveofsins.com, archive.nyafuu.org, rbt.asia to ChanRipper as requested in https://github.com/RipMeApp/ripme/issues/38#issuecomment-485391989
Fix regex to allow TLDs with len of 4
> New Chans to ChanRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/video/PornhubRipper.java
Download was failing on some Pornhub videos due to the upsell format being used.  These are blank unless you pay for them.  Fix was to ignore any quality entries that had the upsell format.
> Pornhub upsell fix

- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/XhamsterRipperTest.java
Fixed xhamster ripper and added support for the xhamster2.com and xhamster.desi domains
All Xhamsters tests were marked @Test and tests for the new domains were added
> Xhamster domain fixes

- src/main/java/com/rarchives/ripme/ui/UpdateUtils.java
Fixes the update batch file to work in directories with spaces.
Result:
```@echo off
timeout 1
copy "ripme.jar.update" "D:\Cloud\GitHub\ripme\target\ripme-1.7.84-jar-with-dependencies.jar"
del "ripme.jar.update"
"D:\Cloud\GitHub\ripme\target\ripme-1.7.84-jar-with-dependencies.jar"
del "D:\Cloud\GitHub\ripme\target\update_ripme.bat"
```
> Fixes: #1351 ... auto update stopped working

- src/main/java/com/rarchives/ripme/ripper/rippers/GfycatRipper.java
Fixes the issue where the app was unable to rip a gfycat URL starting with thumbs.
URL tested:
* https://gfycat.com/@ehaydon
* https://gfycat.com/powerfulgoodaustraliansilkyterrier-drinking-thirsty-cats
* https://www.gfycat.com/angryblaringguineapig-cat-jfaoiwejfoewjfpoawej
* https://thumbs.gfycat.com/ShadowyDiligentHuemul-mobile.jpg
* https://thumbs.gfycat.com/ParallelSpectacularAmmonite-size_restricted.gif
> Fixes: #1395 ... gfycat-ripper does not rip URL starting with thumbs.gfycat.com

- src/main/java/com/rarchives/ripme/ripper/AbstractHTMLRipper.java
- src/main/java/com/rarchives/ripme/ripper/AbstractJSONRipper.java
- src/main/java/com/rarchives/ripme/ripper/AbstractRipper.java
* `AbstractHTMLRipper` now extends `AbstractRipper`.
* `AbstractJSONRipper` now extends `AbstractRipper`.
* Copied concrete methods from `AlbumRipper` to  `AbstractHTMLRipper` and  `AbstractJSONRipper`.
> Removal of AlbumRipper.

- src/main/java/com/rarchives/ripme/ripper/rippers/MyreadingmangaRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MyreadingmangaRipperTest.java
A ripper and unit test for Myreadingmanga.info
> Added ripper for Myreadingmanga.info

- src/main/java/com/rarchives/ripme/ripper/rippers/MotherlessRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/NewsfilterRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/NfsfwRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/PornhubRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/VkRipper.java
Am slowly removing references to AlbumRipper according to #423.
Don't merge yet, still a work in progress.
> [WIP] Removal of references to AlbumRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/ListalRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ListalRipperTest.java
- A new ripper for `listal.com`.
- Supported url types:
`https://www.listal.com/tvMovieOrSomething/batcave/pictures` and
`https://www.listal.com/list/most-influent-guitarists-history`
- closes #1184 
> Added Listal Ripper.

- src/main/java/com/rarchives/ripme/ripper/rippers/GfycatRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/GfycatRipperTest.java
Adding a string replace to remove the "/amp"
> Fix #1416 - Fails to download gfycat.com/amp/*

- src/main/java/com/rarchives/ripme/ripper/rippers/MeituriRipper.java
Also change website regex like I mentioned in a comment in #1360
On some pages number of images that I gathered from the page, that I needed to generate image links were displayed on 2nd row instead of 3rd. My method of getting number of images were ugly and looked at the 3rd row all the time regardless of what's there. This new method actually looks for the info I need (number of images) using regex and not arbitrary places on the page hoping for the info I need.
I've also changed the website regex a tiny bit as I mentioned in my comment in #1360.
> Functional regex for getting image url list (MeituriRipper)

- src/main/java/com/rarchives/ripme/ui/MainWindow.java
Fix queue count update when queue is empty
> Fix queue count update when queue is 0

- src/main/java/com/rarchives/ripme/ripper/rippers/ArtAlleyRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/BaraagRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/MastodonRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/MastodonXyzRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/PawooRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ArtAlleyRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/BaraagRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MastodonRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MastodonXyzRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/PawooRipperTest.java
I've added a basic Mastodon ripper and several rippers that extend it for various Mastodon instances. This includes mastodon.social, mastodon.xyz, artalley.social, pawoo.net, and baraag.net. It downloads a single user's full media gallery, by scraping the web interface instead of via the API, so no authentication is required.
It accepts URLs in the form `https://[host]/@[user]`, with an optional `/media` suffix appended if not specified.
The following URLs were tested and work as expected:
```
https://mastodon.social/@pythonhub/media
https://mastodon.xyz/@artwo/media
https://artalley.social/@curator/media
https://pawoo.net/@halki/media
https://baraag.net/@darkshadow777/media
```
> Mastodon rippers

- src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/XvideosRipper.java
Fixed xhamster ripper not downloading after 30 images.
> Fixed xhamster ripper not downloading after 30 images

- src/main/java/com/rarchives/ripme/ripper/rippers/AllporncomicRipper.java
Ripper now accepts link ending with a / and links to series pages 
> Allporncomic ripper fix

- src/main/java/com/rarchives/ripme/ripper/rippers/FolioRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FolioRipperTest.java
- A new ripper for folio.ink
- Example supported URL: ```https://folio.ink/DmBe6i```
> Add Ripper for folio.ink

- src/main/java/com/rarchives/ripme/ripper/rippers/MeituriRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/VkRipper.java
Meituri: Protocoll changed to http**s** because http access doesn't work anymore (HTTP answer 403). Test was already set up on https.
VK: Download of albums works now
> Fix MeituriRipper and VKRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/InstagramRipperTest.java
Stories ripping fixed.
qHash is now extracted with js parsing instead of regex.
> InstagramRipper fixed

- src/main/java/com/rarchives/ripme/utils/Utils.java
- src/test/java/com/rarchives/ripme/tst/UtilsTest.java
Shortens max path name on windows to 259 chars
> Fixed path name issues on windows

- src/main/java/com/rarchives/ripme/ripper/rippers/video/PornhubRipper.java
The video URL is now "encrypted" by splitting it up in variables. This change was adopted in the this code.
The video URL is now "encrypted" by splitting it up in variables. This change was adopted in the this code.
> Fix Pornhub Video Ripper

- src/main/java/com/rarchives/ripme/utils/Http.java
- src/main/java/com/rarchives/ripme/utils/RipUtils.java
Many resources could be downloaded by ripme, but are hidden behind a login. Users that have accounts with these services can access the content, but ripme can't.
Since most websites use cookies to store the logged in state in the browser, we can use them to log in. We need to use the cookies the user has in the browser and send them with our requests.
(this should also be a wiki entry if accepted)
To use the cookies feature, the cookies need to be supplied in the [config file](https://github.com/RipMeApp/ripme/wiki/Config-options), in a line like this: `cookies.host = key1=val1; key2=val2`. 
To get them, go to the website for which you want to get cookies, e.g. https://reddit.com.
Open the browser console (e.g. using F12; right click & inspect …
> Add cookie support for all rippers

- pom.xml
- src/main/java/com/rarchives/ripme/ripper/rippers/VkRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/VkRipperTest.java
* Fixed pattern in `getGID` function.
* Reverted unintended changes from @felixaufreisen.
His VkRipper fix #1481. 
Possibly unintended changes in #1485 .
* Moved multiple paginated requests logic from `getFirstPage` to `getPage` function.
* Implemented `nextPage` using the `getPage` function.
* Ripper now downloads images in the highest possible resolution.
* Bumped json library version from `20140107` to `20190722`
> Fixed VkRipper and bumped JSON library.

- src/main/java/com/rarchives/ripme/ripper/rippers/LusciousRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/LusciousRipperTest.java
* Changed regex pattern to match `https://www.luscious.net/...`,  `https://old.luscious.net/...`, `https://members.luscious.net/...`.
* Added overrides for `sanitizeUrl` and `normalizeUrl`.
* Re-enabled test cases.
> Fixed LusciousRipper.

- src/main/java/com/rarchives/ripme/ripper/rippers/PawooRipper.java
The generic Mastodon ripper mostly worked as a base for this ripper, but Pawoo uses an alternate web UI that changes how navigation links work, so I've updated it to use the correct selector. Before this change, only the first page of the media for a user was ripped.
As an aside, I really like how we're forcing Travis to repeatedly rip loads of porn.
> Fix Pawoo ripper pagination

- src/main/java/com/rarchives/ripme/ripper/rippers/ArtStationRipper.java
HTTP compression resulted in non-readable html, therefore it was deactivated.
> ArtStationRipper Fix

- src/main/java/com/rarchives/ripme/ripper/rippers/ReadcomicRipper.java
Added ripper for view-comic proxy(?) site read-comic
> Added read-comic.com ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/ImagefapRipper.java
Only changed `http` to `https` 
Since some users are experiencing problem with `http` version of imgaefap, `https` should be used.
> Changed imagefap links from http to https

- src/main/java/com/rarchives/ripme/ripper/rippers/FreeComicOnlineRipper.java
Added a ripper for freecomiconline.me supports chapter download and continues to next chapter until caught up
> Added FreecomiconlineRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/E621Ripper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/E621RipperTest.java
Changed e621 ripper to work with the updated e621 site. Added bypass for Cloudflare captcha and global anonymous user blacklist, which were added with this update. Created new config options e621.cookies and e621.useragent for this purpose.
> Updated e621 ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/MotherlessRipper.java
Due to an update of the site's HTML an CSS selector needed to be changed. The download of galleries works just fine now.
> Fix MotherlessRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/GfycatRipper.java
> Now sends a referrer when fetching first page

- src/main/java/com/rarchives/ripme/ripper/rippers/VscoRipper.java
URL format was changed from `https://vsco.co/<username>/images/1` to `https://vsco.co/<username>/gallery` and an error occured when entering an URL of the new scheme. The corrosponding regular expressions were adopted. Now URLs of following formats are allowed and work:
- `https://vsco.co/<username>`
- `https://vsco.co/<username>/`
- `https://vsco.co/<username>/gallery`
- `https://vsco.co/<username>/gallery/`
> VscoRipper Fix

- src/main/java/com/rarchives/ripme/ripper/rippers/RedgifsRipper.java
- src/main/java/com/rarchives/ripme/utils/RipUtils.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/RedgifsRipperTest.java
- Using similar functionality found in the gfycat ripper the same was done for the redgifs ripper
- A user's profile can be ripped, by retrieving all gfycats from their user api call
- The categories and search ripper is also implemented but uses and incrementing start and count in the api url paramters as the cursor requires cookies (I believe) to work and this one just increments until there are no gfycats and returns error (there are no more gfycats)
- Differentiated between getting profile and search urls using regex matching
COMMIT-2 
- Changed redgifs api URL to reflect updated change
- Added check in getNextPage to see if page has any URLs else finishes rather than throwing error
- Added …
> RedgifsRipper: Implemented redgifs.com Ripper

- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
Fix log by adding space before URL
> Fix malformed log on file already exist

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaiNexusRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentainexusRipperTest.java
Added a ripper for HentaiNexus
> Added ripper for HentaiNexus

- src/main/java/com/rarchives/ripme/ripper/rippers/XcartxRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/XlecxRipper.java
xlecx has changed its URL from 'xlecx.com' to 'xlecx.org'.
This change modifies the ripper.java to reflect that change, and to add the required https prefix.
(If the https prefix is not added, the image download fails with 'no protocol'. That seems a little janky, but it was used in #120.)
This pull resolves Issue #1696
Regarding _mvn test_, it has errors both before and after my changes... So I guess that counts as 'no _new_ failures'?
Please advise on how to do that better if I ought to.
Regarding a unit test, the unit test supplied when the xlecx ripper was first added in Merge #1206 should suffice, although I don't see it in the files anymore. …
> Resolve xlecx error #1696

- src/main/java/com/rarchives/ripme/utils/Http.java
The condition for the while loop was causing the config cookie search to break after only checking the full domain, instead of trying higher-level domains. For example www.imagefap.com would be tried but not imagefap.com.
> Fix early termination bug in cookiesForURL

- pom.xml
- src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java
This PR attempts to fix the instagramRipper, #1598 #1699 #1715 #1719 . I've replaced nashorn with GraalVM.js, which makes the binary a lot bigger. So I'm not sure how I feel about that.
Would appreciate your thoughts on this, perhaps a different way to reliably extract the qHash.
> fix: instagramRipper, replaced Nashorn with GraalVM.js

- .github/workflows/maven.yml
- README.md
- pom.xml
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/CheveretoRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ErotivRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FolioRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FooktubeRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FuraffinityRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/GfycatporntubeRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImagefapRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImgurRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/LusciousRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/PichunterRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/RedditRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/RedgifsRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/RippersTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/TheyiffgalleryRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/TwitterRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/WordpressComicRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/XhamsterRipperTest.java
* [ x] a new feature
allow switching off slow tests via command line by adding a tag, description on how to do it in commit message. slow tests are run by default. the same principle is used to switch off flaky tests. they are not run by default to get a green build. as jdk-9 died out, replace it with jdk-14 for the build matrix. number of failing tests and reasons for failure stay the same.
* [x ] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [ x] I've verified that this change works as intended.
* [x ] Downloads all relevant content.
* [x ] Downloads content from multiple pages (as necessary or appropriate).
* [ x] …
> Junit5 allow switch off slow or flaky tests

- src/main/java/com/rarchives/ripme/ripper/rippers/MangadexRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MangadexRipperTest.java
Added functionality to rip entire manga instead of just single chapter.Only supports english language.
All chapters are saved in one folder.
> Added option to download entire manga from mangadex

- src/main/java/com/rarchives/ripme/ripper/rippers/PawooRipper.java
Ripper was previously only downloading one page. Now it downloads all pages.
Downloaded images from from an an individuals profile on pawoo.
> Pawoo no longer has a custom theme

- src/main/java/com/rarchives/ripme/ripper/rippers/AllporncomicRipper.java
unit test failed, now green again.
* [ x] a bug fix (Fix #...)
* [x ] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x ] I've verified that this change works as intended.
* [x ] Downloads all relevant content.
* [x ] I've verified that this change did not break existing functionality (especially in the Ripper I modified).
> src --> data-src in AllporncomicRipper

- src/main/java/com/rarchives/ripme/ripper/rippers/RedditRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/RedditRipperTest.java
A gallery is a special kind of reddit post, which can have up to 20
images. They can be recognized by the is_gallery field in the JSON.
The gallery_data array describes the structure of the gallery by
referencing the image ids, it also contains the captions and links, which
are ignored by this implementation. The s field of each entry in
media_metadata array appears to reference the highest quality image.
> RedditRipper: added gallery support

- src/main/java/com/rarchives/ripme/ripper/rippers/GfycatRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/GfycatRipperTest.java
Gfycat allows special chars in the username (dot, hyphen and underscore) but only letters and numbers were included in the username regex used to call the API and get the download links.
Fixed the issue, "cleaned" the regex and added a new test.
> Fixed #1795 and added new test

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaiNexusRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentainexusRipperTest.java
Tests for HentaiNexusRipper were failing so I went to fix it, they added some obfuscated JavaScript code to hide the image URLs and changed the whole page.
Please forgive me for the (in my opinion) poor quality of the test code and especially for the lack of comments in the *decodeJsonString* function but as you can see there is no real logic, it's just some "random" byte swap and substitution. Deobfuscating the JavaScript function and porting it to Java was really hard and I really don't know what to write in the comments to explain it other than just translating from Java to human language every operation.
Feel free to request more if you feel the code is not good enough. …
> Fixed ripper for HentaiNexus

- src/main/java/com/rarchives/ripme/App.java
-r and -R options were running before setting the rips directory, moving this option to before allows users to set a directory for rerips when run from CLI.
> Move -l option up to allow setting path for -r/-R

- src/main/java/com/rarchives/ripme/ripper/rippers/RedditRipper.java
Category
Edited RedditRipper#handleGallery() method to include gif urls.
> Added extra condition to include reddit gallery gifs urls 

- src/main/java/com/rarchives/ripme/ripper/DownloadFileThread.java
A code block was added where the NullPointerException is controlled, since having an album and multiple multimedia files, the videos (more specifically the mp4 formats) cannot be downloaded. Therefore, it alerts the user when the file cannot be downloaded and in this case it does not try to download it again.
* [x ] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [ x] I've verified that this change works as intended.
* [ x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).
> NullPointerException handled for invalid save path. #1785

- src/main/java/com/rarchives/ripme/ripper/rippers/EromeRipper.java
Erome ripper returned error 405 trying to download images and videos due to the absence of its referer property. Adding the website referer string to the ripper fixed the issue.
> Added referer to avoid 405 error in downloads

- src/main/java/com/rarchives/ripme/ripper/rippers/DanbooruRipper.java
- src/main/java/com/rarchives/ripme/utils/Http.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/BooruRipperTest.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/DanbooruRipperTest.java
Adds support and tests for danbooru.donmai.us as requested in #1644
- Now you can download the content from Danbooru by tag.
- Add tests to BooruRipper and new DanbooruRipper.
- Add the method getJSONArray() in class Http class to obtain an array JSON.
> Added Danbooru ripper and tests

- src/main/java/com/rarchives/ripme/ripper/rippers/WebtoonsRipper.java
Fix Webtoons (disable Age Gate)
Test was redirected to a "verify age" page, this is avoided by setting cookies
> Fix Webtoons (disable Age Gate)

- src/main/java/com/rarchives/ripme/ripper/rippers/WordpressComicRipper.java
Fix WordpressComic
Page layout changes to:
freeadultcomix.com
shipinbottle.pepsaga.com
> Fix WordpressComic

- README.md
* a bug fix (Fix #...)
* a new Ripper
* a refactoring
* a new feature
Hi! I was the primary maintainer of ripmeapp/ripme from about 2016-2018. I'm pleased to see that while that repo was abandoned, a fork of the project continued over here. I'm back to poke around a bit and wanted to sync up the repo as well as make it clear who the primary developer is on the project now. I've also made an announcement post on the subreddit to point to the new active development repo.
I've pushed the main of ripmeapp2/ripme to ripmeapp and I want to make this change as well to both repos to make it clear where active development is happening and who is the current primary developer.
I'm not guaranteeing I'll …
> Update README.md: remove donation links, update maintainer list, announce merge of ripmeapp2 back into ripmeapp

- README.md
- src/main/java/com/rarchives/ripme/ripper/AbstractHTMLRipper.java
- src/main/java/com/rarchives/ripme/ripper/AbstractJSONRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/LusciousRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/NudeGalsRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/XvideosRipper.java
- src/main/java/com/rarchives/ripme/ripper/rippers/video/MotherlessVideoRipper.java
* a bug fix (Fix #...)
* a new Ripper
* a refactoring
* a new feature
* I've added a unit test to cover my change.
> Fix usage of deprecated URL constructors, which found a couple of issues

- src/main/java/com/rarchives/ripme/ripper/rippers/XvideosRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/XvideosRipperTest.java
Also, extract patterns to be compiled once in static members to avoid repeating the match patterns and make the code read a little more clearly.
Improve album name for the video case.
* a new Ripper
* a refactoring
* a style change/fix
* a new feature
* Note: an issue of concern - I'm not clear on why the existing unit test didn't catch this issue in the first place. Maybe because it effectively did nothing and didn't fail.
> Fix XvideosRipper: update URL pattern to match current URL scheme.

- src/main/java/com/rarchives/ripme/ripper/rippers/FapDungeonRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FapDungeonRipperTest.java
* a bug fix (Fix #...)
* a refactoring
* a style change/fix
* a new feature
Implemented FapDungeon ripper, as requested in RipMeApp/ripme#1979. As implemented, this works to get the largest resolution available of all images and videos, as tested on the 3 URLs in the unit test file.
> Implement FapDungeonRipper (Issue #1979)

- src/main/java/com/rarchives/ripme/ripper/rippers/NsfwAlbumRipper.java
I've gone ahead and added a ripper for nsfwalbum.com. 
They host their images on many different image hosting sites so you must replace part of the image urls to get the full image instead of the thumbnails.
There may be more hosts that I did not find, they can be added in later very easily.
NOTES: 
mvn test failed, i think it may because of how my maven is setup, it doesnt reference any files of ripme in the stacktrace, i can post the error if that is helpful.
I don't have any experience on how to do unit testing, I am eager to learn if someone wants to help and give me a quick run down.
> Add Ripper for nsfwalbum.com

- .github/workflows/gradle.yml
From the Java SE Support Roadmap (see https://www.oracle.com/java/technologies/java-se-support-roadmap.html)
Java 17 LTS is supported (from "Premiere Support" column) until "September 2026, or later", so it is reasonable to keep ensuring compatibility with Java 17.
As for Java 21 LTS, even though it has been in General Availability (GA) since September 2023, Debian only has the OpenJDK 21 package in `testing` and `unstable` -- see https://tracker.debian.org/pkg/openjdk-21
> Reset Java minimum version to Java 17 (OpenJDK 17), to support Debian (Closes #2055)

- src/main/java/com/rarchives/ripme/ui/ClipboardUtils.java
Can now rip links including @ from the clipboard 
> Rewrote ClipboardUtils regex (Fixes #1350)

- src/main/java/com/rarchives/ripme/ripper/rippers/NudeGalsRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/NudeGalsRipperTest.java
Added support for nude-gals.com video pages like https://nude-gals.com/video.php?video_id=1277 (NSFW)
> Add Nude-Gals video support

- src/main/java/com/rarchives/ripme/ui/MainWindow.java
Set fixed size to historyButtonPanel
> Set fixed size to historyButtonPanel

- src/main/java/com/rarchives/ripme/ripper/rippers/FapwizRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/FapwizRipperTest.java
Gfycatporntube changed and now redirects to Fapwiz, but a simple change to that ripper didn't just work, so I removed Gfycatporntube already, and now I've implemented Fapwiz.
> Implement Fapwiz Ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/TumblrRipperTest.java
* Tumblr audio download
I've added support for batch downloading audio in Tumblr posts.
```
./gradlew testAll --tests TumblrRipperTest.testTumblrAudioRip
```
> added audio post downloading support for tumblr + test

- src/main/java/com/rarchives/ripme/ripper/rippers/ChanRipper.java
Fix downloading 4chan threads that contain videos by adding a delay to avoid rate limiting.
> ChanRipper: Add a delay before downloading videos to avoid rate limiting related to specifically videos (fixes #2049)

- src/main/java/com/rarchives/ripme/ui/MainWindow.java
The "about" dialog accessible from the system tray icon had too much content without a scrollview that made the dialog too tall. This changes it so that the long list of sites supported is inside of a scrollview.
> Add a ScrollView to hold the list of supported sites in the About dialog (Fixes #2104)

- src/main/java/com/rarchives/ripme/ripper/rippers/CfakeRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/CfakeRipperTest.java
Cfake site changed URL and layout. This PR fixes the ripper to align with the new site layout.
> Update CfakeRipper to new site format (Fixes #2116)

- src/main/java/com/rarchives/ripme/ripper/rippers/HentaiimageRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentaiimageRipperTest.java
The URL changed. Updated the ripper and test.
> Update HentaiimageRipper for new URL (Fixes #2122)

- src/main/java/com/rarchives/ripme/ripper/rippers/MrCongRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/MrCongRipperTest.java
This ripper was previously for mrcong.com, which now redirects to
misskon.com. Some resources still refer to mrcong.com
but all the top level URLs are now misskon.com
> Fix MrCongRipper to use new URL misskon.com (Fixes #2127)

- src/main/java/com/rarchives/ripme/ripper/rippers/HypnohubRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/HypnohubRipperTest.java
Fixed HypnoHub ripper to work with the new url format. Modified the requisite unit test case for the ripper.
> Fixes to Hypnohub Ripper

- src/main/java/com/rarchives/ripme/ripper/rippers/DribbbleRipper.java
- src/test/java/com/rarchives/ripme/tst/ripper/rippers/DribbbleRipperTest.java
The site changed its layout, so the original logic for parsing image URLs no longer works. This PR updates the logic to get the largest image URL from the `<img>` element inside each `div.shot-thumbnail-base`.
> Fix DribbbleRipper to get image URLs
