patch.py

Added python patch script for *nix systems

Add python patch script

---

README.md

Update Readme file with the right dependencies

---

src/main/java/com/rarchives/ripme/ui/MainWindow.java

Maybe now I get along with GitHub ...
Just merely wrapped the function call in an empty `try...switch` statement, so it should work as is, and I can't test, yet.

Make tray icon optional

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/BasicRippersTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/InstagramRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/VideoRippersTest.java

I removed some urls that were 404ing and replaced them with non-404ing urls

Unit test fixes

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/BasicRippersTest.java

I changed 2 urls that were 404ing to non-404ign urls

Some minor unit test fixes

---

src/main/java/com/rarchives/ripme/App.java
src/main/java/com/rarchives/ripme/ripper/rippers/AerisdiesRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/CfakeRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/CheveretoRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/EroShareRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/EromeRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/HbrowseRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/Hentai2readRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/HentaiCafeRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/JagodibujaRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/LusciousRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/MyhentaicomicsRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/PorncomixRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/SinnercomicsRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/ThechiveRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/WebtoonsRipper.java
src/main/java/com/rarchives/ripme/utils/Utils.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/BasicRippersTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImgurRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/RippersTest.java

Removed unused imports

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/ChanRipperTest.java

I removed unit tests for sites that no longer exists and replaced 404ing links with none 404ing links

Fixed broken unit tests

---

src/main/java/com/rarchives/ripme/ripper/rippers/ModelmayhemRipper.java

I completely rewrote the ripper because it was quite outdated; it can now rip image from Modelmayhem without issue
Test link: https://www.modelmayhem.com/portfolio/520206/viewall

Fixed Modelmayhem ripper

---

src/main/java/com/rarchives/ripme/ripper/rippers/PichunterRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/BasicRippersTest.java

Added a new ripper for pichunter.com

Added ripper for Pichunter.com

---

src/main/java/com/rarchives/ripme/App.java
src/main/java/com/rarchives/ripme/ripper/rippers/video/MotherlessVideoRipper.java
src/main/java/com/rarchives/ripme/ui/UpdateUtils.java
src/main/java/com/rarchives/ripme/utils/RipUtils.java

I changed all print statements to use logger

Logging fixes

---

README.md

People have expressed interest in donating, and we wouldn't mind getting tips. We've set up a PayPal. This change adds links to the README.
N/A

Update README with donation links.

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/FuskatorRipperTest.java

Re-enabling test that passed locally -- we'll see what happens in the CI.

Re-enable FuskatorRipperTest since there doesn't seem to be anything wrong.

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/RedditRipperTest.java

Re-enable Reddit tests.

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/AerisdiesRipperTest.java

Add AerisdiesRipperTest

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/EhentaiRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/Hentai2readRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/HentaicafeRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/MyhentaicomicsRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/PorncomixRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/SinnercomicsRipperTest.java

I added unit tests for hentaicafe, myhentaicomics, e-hentai, sinnercomics, porncomix and hentai2read

Added more unit tests

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/WebtoonsRipperTest.java

Add WebtoonsRipperTest

---

src/main/java/com/rarchives/ripme/ui/MainWindow.java

I added 2 new funcs (addNewCheckbox and addCheckboxListener) that allowed me to cut down some repetitive code 

UI refactoring 

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/BcfakesRipperTest.java

BcfakesRipperTest

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/CfakeRipperTest.java

CfakeRipperTest

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/E621RipperTest.java

E621RipperTest

---

src/main/java/com/rarchives/ripme/ripper/rippers/E621Ripper.java

I changed the ripper so it now gets the full sized image from the images webpage, instead of trying to get it from the thumbnail, however because of that the ripper is rather slow now.

Fixed E621 Ripper

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/XbooruRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/ZizkiRipperTest.java

I added unit tests for zizki.com and xbooru.com

More unit tests

---

src/main/java/com/rarchives/ripme/ripper/rippers/RedditRipper.java

I changed the reddit useragent to point to the current repo and maintainers.

Updated reddit user agent

---

docs/options.md

I added documentation for some of ripmes config options.

Added basic docs for some of ripmes options

---

src/main/java/com/rarchives/ripme/ui/MainWindow.java

[x] closes an issue #95 
added additional button for clearing history

added additional button for clearing history

---

src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java

The ripper will now print the message "Tumblr rate limit has been exceeded" both to the log and to the message field and end the current rip if tumblr returns a 429 error

Tumblr ripper now tells the user if it hits the rate limit

---

src/main/java/com/rarchives/ripme/ripper/rippers/FuraffinityRipper.java

I made a account for ripme, got the cookies and added them to the ripper.

FuraffinityRipper can now rip non-public albums

---

src/main/java/com/rarchives/ripme/ripper/rippers/video/GfycatRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/GfycatRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/RedditRipperTest.java

Added sanitization, and appropriate tests.
- Rips from reddit go in Reddit Test Suite
- Direct rips from Gfycat go in the Gfycat Test Suite

Gfycat fix and test

---

pom.xml
ripme.json
src/main/java/com/rarchives/ripme/ui/UpdateUtils.java

Added VSCO Ripper suggested in #38.
Currently only supports ripping single images, pushing this out ASAP in case someone needs it.
The problem right now is with the Javascript changing the DOM, so Jsoup does not work properly. Maybe this will have to be a JSON ripper?

VSCO Ripper

---

src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java

The ripper now rips images as it finds them, which speeds up ripping considerably. 

Eigthmuses ripper now uses ASAP ripping

---

src/main/java/com/rarchives/ripme/ripper/rippers/video/PornhubRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/VideoRippersTest.java

Fix for pornhub caused by website change

Pornhub fix

---

build.sh

Added shebang line to build.sh

Added shebang line to build.sh

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/FivehundredpxRipperTest.java

The Fivehundredpx Ripper is broken; The test has been disabled for now

Disabled FivehundredpxRipper test

---

src/main/java/com/rarchives/ripme/ripper/rippers/video/XvideosRipper.java

The ripper now gets the video url from the HTML5 player instead of trying to get it from the flash player (Which no longer shows by default)

Fixed xvideos ripper

---

src/main/java/com/rarchives/ripme/ripper/rippers/StaRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/StaRipperTest.java

Added sta ripper

---

README.md

I added some more features to the features list in the readme

Added more features to readme

---

src/main/java/com/rarchives/ripme/ripper/rippers/ModelxRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/ModelxRipperTest.java

Added a ripper for [modelx.org ](http://www.modelx.org/) (NSFW).

Added modelx ripper

---

src/main/java/com/rarchives/ripme/ripper/rippers/BlackbrickroadofozRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/CfakeRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/EightmusesRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/EroShareRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/FuraffinityRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/LusciousRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/MyhentaicomicsRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/SinfestRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/ViewcomicRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/WordpressComicRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
src/main/java/com/rarchives/ripme/ripper/rippers/video/XvideosRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/AerisdiesRipperTest.java

Some minor code clean up (Making sure string comparisons use .equals, removing unused imports ect)

Some minor code clean up

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/EightmusesRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/ModelmayhemRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/MyhentaicomicsRipperTest.java

Extended some unit tests to include getGid

---

src/main/java/com/rarchives/ripme/ripper/rippers/Rule34Ripper.java
src/main/java/com/rarchives/ripme/ripper/rippers/rule34Ripper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/Rule34RipperTest.java

I added a unit test and ripper for rule34.xxx

Rule34 xxx ripper

---

src/main/java/com/rarchives/ripme/ripper/rippers/ManganeloRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/ManganeloRipperTest.java

Added ManganeloRipper

---

src/main/resources/LabelsBundle_pt_PT.properties

I decided to help with the portuguese translation of the original LabelsBundle.properties file, I hope it's just as accurate as the english version!

Portuguese from Portugal translation

---

src/main/java/com/rarchives/ripme/ui/MainWindow.java
src/main/java/com/rarchives/ripme/utils/UTF8Control.java
src/main/java/com/rarchives/ripme/utils/Utils.java
src/main/resources/LabelsBundle.properties
src/main/resources/LabelsBundle_de_DE.properties
src/main/resources/LabelsBundle_es_ES.properties
src/main/resources/LabelsBundle_fr_CH.properties
src/main/resources/LabelsBundle_pt_PT.properties

Added a Spanish translate (by @Isaaku), did some work on the UI so it actually uses provided translations

Translations

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/VideoRippersTest.java

Disabled the test for the twitch ripper

Disabled test for broken ripper

---

src/main/resources/LabelsBundle_id_ID.properties

@biladina's Bahasa Indonesia Translation
I take no credit, just pushing it to the repo.

@biladina's Bahasa Indonesia Translation

---

src/main/java/com/rarchives/ripme/App.java
src/main/java/com/rarchives/ripme/utils/Utils.java

Comments for every method in App.java and Utils.java
Will be working through all old core classes soon enough.

The Road to Javadoc, Part 1: Prithee, peace

---

src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java

I rewrote the ripper to use abstractJSONRipper, completely side stepping the issue cause by Jsoup mentioned in #601 

Fixed instagram ripper

---

src/test/java/com/rarchives/ripme/tst/Base64Test.java

Added a unit test for the base64.decode func

Added base64 unit test

---

src/main/java/com/rarchives/ripme/ripper/AbstractJSONRipper.java

Fix history again

---

src/main/java/com/rarchives/ripme/ripper/rippers/TumblrRipper.java

I replaced a bugged string replace that was changing all https links to httpss and added a func to pick a random api key

Fixed tumblr api key selection and video downloading

---

README.md

I added a note about the tag skip feature and a link to the wiki

Added tag skip feature to features list

---

release.py

added --test option for dry runs
release script now makes sure update file is named ripme.jar; added --test flag for doing dry runs

release script now makes sure update file is named ripme.jar

---

src/main/java/com/rarchives/ripme/utils/Utils.java

Refactoring in Utils class

---

patch.py

This fixes a bug that was introduced in #735 which caused patch.py to set the change list to null

Patch script fixes

---

src/main/java/com/rarchives/ripme/ripper/rippers/LoveromRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/LoveromRipperTest.java

Added a ripper for loveroms.com

Loverom ripper [WIP]

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/LoveromRipperTest.java

Removed failing unit test

---

src/main/java/com/rarchives/ripme/ripper/AbstractHTMLRipper.java

Removed outdated todo

---

src/test/java/com/rarchives/ripme/tst/UtilsTest.java

Added some more unit tests

---

src/main/java/com/rarchives/ripme/ui/MainWindow.java

This PR adds the ability to rip all urls in a text file from the gui (same as the -f flag). This feature was requested in #870

Added ability to rip file of urls from the gui

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/HbrowseRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/JabArchivesRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/JagodibujaRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/LusciousRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/NewsfilterRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/PahealRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/RajceRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/ThechiveRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/TsuminoRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/ViewcomicRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/tamindirmp3Test.java

See issues #915, #916, #917, #918, #919, #920, #921, #922, #923, #924, #925

Added Test file stubs for rippers that did not have corresponding test files.

---

deploy.bat
src/main/java/com/rarchives/ripme/ripper/rippers/video/MulemaxRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/MulemaxRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/StickyXXXRipperTest.java

Ripper and Unit test for Mulemax.com

Mulemax.com Ripper (NSFW)

---

src/main/java/com/rarchives/ripme/ui/MainWindow.java

Added func to write line to both GUI and CLI logs 
Added some documentation to the log functions
Fixed a typo in a comment 

Added func to write line to both GUI and CLI logs

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/ThechiveRipperTest.java

Added unit test for ThechiveRipper

Added unit test for ThechiveRipper

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/VscoRipperTest.java

Replaced 404ing url in VscoRipperTest

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/TumblrRipperTest.java

Commented out a failing unit test

Commented out a failing test for the tumblr ripper

---

src/main/java/com/rarchives/ripme/ripper/rippers/Tubex6Ripper.java

Fixed video downloading for Tubex6 by sending a referrer when downloading the file

Fixed Tubex6Ripper

---

src/main/java/com/rarchives/ripme/ripper/rippers/WordpressComicRipper.java

Added support for http://comixfap.net

Added support for http://comixfap.net

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/SinnercomicsRipperTest.java

Removed a test for sinner comics as the ditr has changed

Disabled unneeded unit test

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/FuraffinityRipperTest.java

Fixed a failing unit test for Furaffinity

Replaced test link

---

src/main/java/com/rarchives/ripme/ripper/rippers/video/PornhubRipper.java

The Pornhub video ripper was not working anymore, it tried using a regex to match a JSON array which was not very clean.
I made it so that it directly uses the JSON array and it now works as far as I can tell.
Also, the quality is now included in the filenames.
The only test failures used to exist before my fix, and don't concern this ripper.
Fixes issue #1095 

Fixed and cleaned up Pornhub video ripper

---

src/main/java/com/rarchives/ripme/ripper/rippers/ImagefapRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImagefapRipperTest.java

Fixed imagefap getAlbumTitle and added a unit test for it
Thanks to @basemann for the code

Imagefap gid fix

---

src/main/java/com/rarchives/ripme/ripper/rippers/ArtStationRipper.java

An issue with the ArtStationRipper where it would end up on clouldflare verification page and fail to rip.
This issue was fixed with minor changes in the `parseUrl()` method( by handling responses with 403 status code, seperately).
As the `jsonUrl` format is  known, appending the `projectId` and returning the `ParsedUrl` object beforehand fixes the problem.

Fixed ArtStation not downloading images.

---

src/main/java/com/rarchives/ripme/ui/UpdateUtils.java

The linux/mac updater no longer uses an external script, since it is possible to modify a file while it is being run without issue.
The windows updater remains the same (batch file). I do not have a windows machine here so I cannot confirm whether this approach could be applied to windows.
Partly fixes #1153 
Note I haven't tested this with windows but it should still work since the procedure is still the same with windows systems.

Updater for Linux/Mac now in pure Java

---

src/test/java/com/rarchives/ripme/tst/ripper/rippers/BlackbrickroadofozRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/SinnercomicsRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/ThechiveRipperTest.java

Removed tests for links/sites that no longer exist

Test fixes

---

src/main/java/com/rarchives/ripme/ripper/rippers/DeviantartRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/DeviantartRipperTest.java

New Deviantart Ripper. HTML based.
NOT using Deviantart API like the old JSON ripper because it is SLOW (and IMHO annoying to use)
Things to consider: Using the API might be less work/maintenance later because APIs do not change as frequently as HTML source code...?
-> had to uncomment something because of new design
-> can basically download galleries, favorites, specific (gallery/fav)folders. Tested with JPG, PNG and PDF

Deviantart Ripper changes

---

src/main/java/com/rarchives/ripme/ripper/rippers/FlickrRipper.java

* [x ] a new feature
This was requested in issue #1324 and was also mentioned in FlickrRipper.java as being on the todo list. The feature simply adds a method to determine the best quality/largest image available using the Flickr API. Best quality is determined by height * width. getURLsFromPage() originally had a primitive method of guessing the largest image but was not very effective and failed to always grab the best quality image.
* [x ] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
only fails were preexisting
* [x ] I've verified that this change works as intended.
* [x ] …

Added method to determine best quality image for flickr ripper [#1324]

---

src/main/java/com/rarchives/ripme/ripper/rippers/NewgroundsRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/NewgroundsRipperTest.java

I made a ripper for Newgrounds requested from https://github.com/RipMeApp/ripme/issues/38#issuecomment-495856932. 
Usage is: https://*username*.newgrounds.com/art

Added Newgrounds Ripper

---

src/main/java/com/rarchives/ripme/ripper/rippers/AllporncomicRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/AllporncomicRipperTest.java

Added a ripper and test for allporncomic.com

Allporncomic ripper

---

src/main/java/com/rarchives/ripme/ripper/rippers/TwitterRipper.java

Fix GIF downloads
Fix GIF Downloads
Fix video dimension using https://github.com/RipMeApp/ripme/issues/1372#issuecomment-511211556
Added download.save_order to avoid prefix when disabled

Fix video dimension

---

src/main/java/com/rarchives/ripme/ripper/rippers/MotherlessRipper.java

Issue #1: If the Homepage of a gallery is opened (path /Gxxxx), theres no next page (path /Gxxxx?page=2). If an homepage link is added, the path is now changed to the "All Uploads" page (path /GMxxxx)
Issue #2: All paths were changed to https:// since insecure connections didn't work with a user
Other Changes:
#1: MotherlessRipper class used to override run method. Now the original method from AbstractHTMLRipper class is used to avoid redundant code.
#2: MotherlessRipper class now implements the getNextPage method. Getting the next page was previously done by the run method. Also the link of the next page is now read from a link-tag in the HTML header and not "calculated" anymore.
Required …

Fixed MotherlessRipper

---

src/main/java/com/rarchives/ripme/ripper/rippers/FitnakedgirlsRipper.java

Added FitnakedgirlsRipper

---

README.md

I created a `cask` for easy installation on macOS and added a note on the docs.

macOS installation docs added

---

src/main/java/com/rarchives/ripme/ripper/rippers/InstagramRipper.java

Fix Instagram ripper fetching only first page

---

README.md

Changed brew installation command from `breww` to `brew`

Fix brew installation command

---

src/main/java/com/rarchives/ripme/ripper/rippers/FlickrRipper.java

Adds proper support from downloading Flickr account images, rather than simply from photosets. Previously, the tool would silently fail on these URLs, claiming the images were downloaded successfully.

Fixed #1196, #1354, #1647, #1693: Added support for ripping entire Flickr profiles

---

src/main/java/com/rarchives/ripme/ripper/rippers/ImagefapRipper.java

Since recently, imgefap now utiliser a flood check. This will prevent ripping at full speed. When lowering the speed of the page calls to 1000 requests per hour, this should avoid triggering the bot check. 
:warning: It's important to note that visiting imagefap while ripping will potentially still trigger their check, as it's IP based.
This is mainly based on @4pr0n check that was written for other rippers.

Fix imagefap ripper to take rate limit into account.

---

src/main/java/com/rarchives/ripme/ripper/rippers/PorncomixinfoRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/PorncomixinfoRipperTest.java

Added porncomixinfo.net ripper and test

Added porncomixinfo.net ripper and test

---

src/main/java/com/rarchives/ripme/ripper/rippers/XhamsterRipper.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/ImagefapRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/PornhubRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/RedditRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/RedgifsRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/XhamsterRipperTest.java
src/test/java/com/rarchives/ripme/tst/ripper/rippers/YoupornRipperTest.java

* [ x] a bug fix (Fix #...)
fix xhamster getTestNextPage, copy 2 lines change from #1798, fix #1777, #1735.
xhamster unit test now green.

fix xhamster testGetNextPage

---

README.md
ripme.json

describe release process
